// <auto-generated />
namespace EF_Inheritence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class varchartovar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(varchartovar));
        
        string IMigrationMetadata.Id
        {
            get { return "201511191309267_varchartovar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
