// <auto-generated />
namespace RU4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201601241827222_initSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
