// <auto-generated />
namespace RU4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class chap5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chap5));
        
        string IMigrationMetadata.Id
        {
            get { return "201601281950271_chap5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
