//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICreditLimitRequest")]
    public interface ICreditLimitRequest {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICreditLimitRequest/SendCreditLimitRequest")]
        void SendCreditLimitRequest(string id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICreditLimitRequest/SendCreditLimitRequest")]
        System.Threading.Tasks.Task SendCreditLimitRequestAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditLimitRequestChannel : Client.ServiceReference.ICreditLimitRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditLimitRequestClient : System.ServiceModel.ClientBase<Client.ServiceReference.ICreditLimitRequest>, Client.ServiceReference.ICreditLimitRequest {
        
        public CreditLimitRequestClient() {
        }
        
        public CreditLimitRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditLimitRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditLimitRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditLimitRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendCreditLimitRequest(string id) {
            base.Channel.SendCreditLimitRequest(id);
        }
        
        public System.Threading.Tasks.Task SendCreditLimitRequestAsync(string id) {
            return base.Channel.SendCreditLimitRequestAsync(id);
        }
    }
}
