//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CreditReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditReference.ICreditLimitRequest")]
    public interface ICreditLimitRequest {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICreditLimitRequest/SendCreditLimitRequest")]
        void SendCreditLimitRequest(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICreditLimitRequestChannel : Client.CreditReference.ICreditLimitRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CreditLimitRequestClient : System.ServiceModel.ClientBase<Client.CreditReference.ICreditLimitRequest>, Client.CreditReference.ICreditLimitRequest {
        
        public CreditLimitRequestClient() {
        }
        
        public CreditLimitRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditLimitRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditLimitRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditLimitRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendCreditLimitRequest(string id) {
            base.Channel.SendCreditLimitRequest(id);
        }
    }
}
