// <auto-generated />
namespace RU1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class studentInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011007587_studentInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
