// <auto-generated />
namespace RU1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class chap4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chap4));
        
        string IMigrationMetadata.Id
        {
            get { return "201512031423009_chap4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
