// <auto-generated />
namespace RU1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class studentModelChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentModelChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201512030928031_studentModelChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
