// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace PTWebAndLoadTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// FullCycle - Use 'FullCycleParams' to pass parameters into this method.
        /// </summary>
        public void FullCycle()
        {
            //Playback.PlaybackSettings.SearchTimeout = 1600000;
            //Playback.PlaybackSettings.SearchTimeout = 1000*60*3;
            //UIMap.ment.WaitForControlReady(1600000);
            //this.UINewtabInternetExplorWindow.WaitForControlReady(1600000);

            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UINewtabInternetExplorWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            WinEdit uIItemEdit = this.UINewtabInternetExplorWindow.UIItemWindow.UIItemEdit;
            HtmlHyperlink uIMicrosoftDynamicsCusHyperlink = this.UINewtabInternetExplorWindow.UIHttpscorpstsmicrosofDocument.UIMicrosoftDynamicsCusHyperlink;
            HtmlDiv uIEmailorphonePane = this.UINewtabInternetExplorWindow.UISignintoyourMicrosofDocument.UICredentialsInputPanePane.UIEmailorphonePane;
            HtmlEdit uILoginfmtEdit = this.UINewtabInternetExplorWindow.UISignintoyourMicrosofDocument.UILoginfmtEdit;
            HtmlDiv uIPasswordPane = this.UINewtabInternetExplorWindow.UISignintoyourMicrosofDocument.UICredentialsInputPanePane.UIPasswordPane;
            HtmlEdit uIPasswdEdit = this.UINewtabInternetExplorWindow.UISignintoyourMicrosofDocument.UIPasswdEdit;
            HtmlInputButton uISigninButton = this.UINewtabInternetExplorWindow.UISignintoyourMicrosofDocument.UISigninButton;
            HtmlRadioButton uIZero2TenInc010535421RadioButton = this.UINewtabInternetExplorWindow.UIMicrosoftDynamicsSelDocument.UIZero2TenInc010535421RadioButton;
            HtmlInputButton uIContinueButton = this.UINewtabInternetExplorWindow.UIMicrosoftDynamicsSelDocument.UIContinueButton;
            HtmlHyperlink uIPartnerFocusHyperlink = this.UINewtabInternetExplorWindow.UIHomeWelcometoPartnerDocument.UIAreanavigationbarCustom.UIPartnerFocusHyperlink;
            HtmlHyperlink uIOrganizationMappingsHyperlink = this.UINewtabInternetExplorWindow.UIHomeWelcometoPartnerDocument.UIAreanavigationbarCustom.UIOrganizationMappingsHyperlink;
            HtmlHyperlink uIItem2382250Hyperlink = this.UINewtabInternetExplorWindow.UIHomeWelcometoPartnerDocument.UIIframeplateFrame.UIOrganizationMappingDocument.UIItem2382250Hyperlink;
            HtmlHyperlink uIManageTaxProfileHyperlink = this.UINewtabInternetExplorWindow.UIHomeWelcometoPartnerDocument.UIIframeplateFrame.UIBankingandTaxEnrollmDocument.UIManageTaxProfileHyperlink;
            HtmlHyperlink uIBackHyperlink = this.UINewtabInternetExplorWindow.UILocationprofilesMicrDocument.UIBackPane.UIBackHyperlink;
            HtmlHyperlink uIRajZero2TenHyperlink = this.UINewtabInternetExplorWindow.UIEmbedWelcometoPartneDocument.UIRajZero2TenHyperlink;
            HtmlHyperlink uISignOutHyperlink = this.UINewtabInternetExplorWindow.UIEmbedWelcometoPartneDocument.UIGlobalNavigationmenuPane.UISignOutHyperlink;
            BrowserWindow uINewtabInternetExplorWindow = this.UINewtabInternetExplorWindow;
            #endregion

            // Go to web page 'about:Tabs' using new browser instance
            //this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.FullCycleParams.UINewtabInternetExplorWindowUrl));

            // Click 'Address and search using Bing' text box
            //Mouse.Click(uIAddressandsearchusinEdit, new Point(234, 9));

            // Type 'businesscenter' in text box
            //Keyboard.SendKeys(uIItemEdit, this.FullCycleParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type 'nebsicrosoft' in text box
            //Keyboard.SendKeys(uIItemEdit, this.FullCycleParams.UIItemEditSendKeys1, ModifierKeys.None);

            // Type 'om{Enter}' in text box
            //Keyboard.SendKeys(uIItemEdit, this.FullCycleParams.UIItemEditSendKeys2, ModifierKeys.None);
            // Click 'Microsoft Dynamics Customers and Partners' link
            //this.UINewtabInternetExplorWindow.CurrentDocumentWindow.WaitForControlReady(-1);
            Playback.PlaybackSettings.SearchTimeout = 1600000;
            uIMicrosoftDynamicsCusHyperlink.WaitForControlReady(-1);
            Mouse.Click(uIMicrosoftDynamicsCusHyperlink, new Point(150, 17));

            // Click 'Email or phone' pane
            Mouse.Click(uIEmailorphonePane, new Point(173, 15));

            // Type 'px3rajesh@outlook.com' in 'loginfmt' text box
            uILoginfmtEdit.Text = this.FullCycleParams.UILoginfmtEditText;

            // Click 'Password' pane
            //Mouse.Click(uIPasswordPane, new Point(138, 22));
            Keyboard.SendKeys(uILoginfmtEdit, "{Tab}", ModifierKeys.None);


            // Type '********' in 'passwd' text box
            uIPasswdEdit.Password = this.FullCycleParams.UIPasswdEditPassword;

            // Click 'Sign in' button
            Mouse.Click(uISigninButton, new Point(209, 15));
            
            //Playback.PlaybackSettings.WaitForReadyLevel = WaitForReadyLevel.AllThreads;
            // Select 'Zero2Ten, Inc. - 0105354218, Acct#5354218, raj@Zer...' radio button
            Playback.PlaybackSettings.SearchTimeout = 1600000;
            this.UINewtabInternetExplorWindow.CurrentDocumentWindow.WaitForControlReady(-1);
            //CurrentDocumentWindow.WaitForControlReady(-1);
            uIZero2TenInc010535421RadioButton.Selected = this.FullCycleParams.UIZero2TenInc010535421RadioButtonSelected;

            // Click 'Continue' button
            Mouse.Click(uIContinueButton, new Point(58, 19));

            // Click 'Partner Focus' link
            Mouse.Click(uIPartnerFocusHyperlink, new Point(145, 38));

            // Click 'Organization Mappings' link
            Mouse.Click(uIOrganizationMappingsHyperlink, new Point(42, 8));

            // Click '2382250' link
            Mouse.Click(uIItem2382250Hyperlink, new Point(33, 6));

            // Click 'Manage Tax Profile' link
            Mouse.Click(uIManageTaxProfileHyperlink, new Point(561, 7));

            // Click 'Back' link
            Mouse.Click(uIBackHyperlink, new Point(25, 4));

            // Click 'raj@Zero2Ten' link
            //Mouse.Click(uIRajZero2TenHyperlink, new Point(107, 5));

            // Click 'Sign Out' link
            Mouse.Click(uISignOutHyperlink, new Point(72, 24));

            // Perform Close on Browser Window
            //uINewtabInternetExplorWindow.Close();
        }
        
        #region Properties
        public virtual FullCycleParams FullCycleParams
        {
            get
            {
                if ((this.mFullCycleParams == null))
                {
                    this.mFullCycleParams = new FullCycleParams();
                }
                return this.mFullCycleParams;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private FullCycleParams mFullCycleParams;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'FullCycle'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class FullCycleParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:Tabs' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "about:Tabs";
        
        /// <summary>
        /// Type 'businesscenter' in text box
        /// </summary>
        public string UIItemEditSendKeys = "businesscenter";
        
        /// <summary>
        /// Type 'nebsicrosoft' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "nebsicrosoft";
        
        /// <summary>
        /// Type 'om{Enter}' in text box
        /// </summary>
        public string UIItemEditSendKeys2 = "businesscenter-pne.mbs.microsoft.com{Enter}";
        
        /// <summary>
        /// Type 'px3rajesh@outlook.com' in 'loginfmt' text box
        /// </summary>
        public string UILoginfmtEditText = "px3rajesh@outlook.com";
        
        /// <summary>
        /// Type '********' in 'passwd' text box
        /// </summary>
        public string UIPasswdEditPassword = "4AU9IRcQ6YD3Oj2IKf2GOs4g9+qU8Ekz";
        
        /// <summary>
        /// Select 'Zero2Ten, Inc. - 0105354218, Acct#5354218, raj@Zer...' radio button
        /// </summary>
        public bool UIZero2TenInc010535421RadioButtonSelected = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.part" +
                    "ners.extranet.");
            this.WindowTitles.Add("Sign in to your Microsoft account");
            this.WindowTitles.Add("Microsoft Dynamics - Select Profile");
            this.WindowTitles.Add("Home | Welcome to PartnerSource Business Center");
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            this.WindowTitles.Add("Location profiles - Microsoft Partners Payee Portal");
            this.WindowTitles.Add("Logout | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIHttpscorpstsmicrosofDocument UIHttpscorpstsmicrosofDocument
        {
            get
            {
                if ((this.mUIHttpscorpstsmicrosofDocument == null))
                {
                    this.mUIHttpscorpstsmicrosofDocument = new UIHttpscorpstsmicrosofDocument(this);
                }
                return this.mUIHttpscorpstsmicrosofDocument;
            }
        }
        
        public UISignintoyourMicrosofDocument UISignintoyourMicrosofDocument
        {
            get
            {
                if ((this.mUISignintoyourMicrosofDocument == null))
                {
                    this.mUISignintoyourMicrosofDocument = new UISignintoyourMicrosofDocument(this);
                }
                return this.mUISignintoyourMicrosofDocument;
            }
        }
        
        public UIMicrosoftDynamicsSelDocument UIMicrosoftDynamicsSelDocument
        {
            get
            {
                if ((this.mUIMicrosoftDynamicsSelDocument == null))
                {
                    this.mUIMicrosoftDynamicsSelDocument = new UIMicrosoftDynamicsSelDocument(this);
                }
                return this.mUIMicrosoftDynamicsSelDocument;
            }
        }
        
        public UIHomeWelcometoPartnerDocument UIHomeWelcometoPartnerDocument
        {
            get
            {
                if ((this.mUIHomeWelcometoPartnerDocument == null))
                {
                    this.mUIHomeWelcometoPartnerDocument = new UIHomeWelcometoPartnerDocument(this);
                }
                return this.mUIHomeWelcometoPartnerDocument;
            }
        }
        
        public UILocationprofilesMicrDocument UILocationprofilesMicrDocument
        {
            get
            {
                if ((this.mUILocationprofilesMicrDocument == null))
                {
                    this.mUILocationprofilesMicrDocument = new UILocationprofilesMicrDocument(this);
                }
                return this.mUILocationprofilesMicrDocument;
            }
        }
        
        public UIEmbedWelcometoPartneDocument UIEmbedWelcometoPartneDocument
        {
            get
            {
                if ((this.mUIEmbedWelcometoPartneDocument == null))
                {
                    this.mUIEmbedWelcometoPartneDocument = new UIEmbedWelcometoPartneDocument(this);
                }
                return this.mUIEmbedWelcometoPartneDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIItemWindow mUIItemWindow;
        
        private UIHttpscorpstsmicrosofDocument mUIHttpscorpstsmicrosofDocument;
        
        private UISignintoyourMicrosofDocument mUISignintoyourMicrosofDocument;
        
        private UIMicrosoftDynamicsSelDocument mUIMicrosoftDynamicsSelDocument;
        
        private UIHomeWelcometoPartnerDocument mUIHomeWelcometoPartnerDocument;
        
        private UILocationprofilesMicrDocument mUILocationprofilesMicrDocument;
        
        private UIEmbedWelcometoPartneDocument mUIEmbedWelcometoPartneDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Address and search using Bing";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpscorpstsmicrosofDocument : HtmlDocument
    {
        
        public UIHttpscorpstsmicrosofDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/adfs/ls/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.partners.extranet.microsoft.com&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fAuthenticationToken.aspx%253fresponse_type%253dtoken%2526redirect_uri%253dhttps%25253A%25252F%25252Fbusinesscenter-pne.mbs.microsoft.com%25252F%252523trust%25252Fsignin&wct=2016-04-20T07%3a30%3a12Z";
            this.WindowTitles.Add("https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.part" +
                    "ners.extranet.");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIMicrosoftDynamicsCusHyperlink
        {
            get
            {
                if ((this.mUIMicrosoftDynamicsCusHyperlink == null))
                {
                    this.mUIMicrosoftDynamicsCusHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIMicrosoftDynamicsCusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "CustomHRD_LinkButton_LiveId";
                    this.mUIMicrosoftDynamicsCusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIMicrosoftDynamicsCusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIMicrosoftDynamicsCusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Microsoft Dynamics Customers and Partners";
                    this.mUIMicrosoftDynamicsCusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "__doPostBack(\'CustomHRD$LinkButton_LiveId\',\'\')";
                    this.mUIMicrosoftDynamicsCusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIMicrosoftDynamicsCusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:__doPostBack(\'CustomHRD$LinkButton_LiveId\',\'\')";
                    this.mUIMicrosoftDynamicsCusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIMicrosoftDynamicsCusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=CustomHRD_LinkButton_LiveId href=\"jav";
                    this.mUIMicrosoftDynamicsCusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIMicrosoftDynamicsCusHyperlink.WindowTitles.Add("https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.part" +
                            "ners.extranet.");
                    #endregion
                }
                return this.mUIMicrosoftDynamicsCusHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIMicrosoftDynamicsCusHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISignintoyourMicrosofDocument : HtmlDocument
    {
        
        public UISignintoyourMicrosofDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in to your Microsoft account";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/login.srf";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp.sts.micr" +
                "osoft.com&wctx=f414e91d-855c-45ca-a877-65ae7b7366e7&wct=2016-04-20T07%3a30%3a12Z" +
                "";
            this.WindowTitles.Add("Sign in to your Microsoft account");
            #endregion
        }
        
        #region Properties
        public UICredentialsInputPanePane UICredentialsInputPanePane
        {
            get
            {
                if ((this.mUICredentialsInputPanePane == null))
                {
                    this.mUICredentialsInputPanePane = new UICredentialsInputPanePane(this);
                }
                return this.mUICredentialsInputPanePane;
            }
        }
        
        public HtmlEdit UILoginfmtEdit
        {
            get
            {
                if ((this.mUILoginfmtEdit == null))
                {
                    this.mUILoginfmtEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginfmtEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "i0116";
                    this.mUILoginfmtEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "loginfmt";
                    this.mUILoginfmtEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginfmtEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginfmtEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginfmtEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control ltr_override";
                    this.mUILoginfmtEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"loginfmt\" class=\"form-control ltr_";
                    this.mUILoginfmtEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILoginfmtEdit.WindowTitles.Add("Sign in to your Microsoft account");
                    #endregion
                }
                return this.mUILoginfmtEdit;
            }
        }
        
        public HtmlEdit UIPasswdEdit
        {
            get
            {
                if ((this.mUIPasswdEdit == null))
                {
                    this.mUIPasswdEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswdEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "i0118";
                    this.mUIPasswdEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIPasswdEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswdEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswdEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswdEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswdEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" class=\"form-control\" id=\"i";
                    this.mUIPasswdEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswdEdit.WindowTitles.Add("Sign in to your Microsoft account");
                    #endregion
                }
                return this.mUIPasswdEdit;
            }
        }
        
        public HtmlInputButton UISigninButton
        {
            get
            {
                if ((this.mUISigninButton == null))
                {
                    this.mUISigninButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISigninButton.SearchProperties[HtmlButton.PropertyNames.Id] = "idSIButton9";
                    this.mUISigninButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISigninButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Sign in";
                    this.mUISigninButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-block btn-primary btn-image btn-image-svg";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-block btn-primary btn-ima";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "20";
                    this.mUISigninButton.WindowTitles.Add("Sign in to your Microsoft account");
                    #endregion
                }
                return this.mUISigninButton;
            }
        }
        #endregion
        
        #region Fields
        private UICredentialsInputPanePane mUICredentialsInputPanePane;
        
        private HtmlEdit mUILoginfmtEdit;
        
        private HtmlEdit mUIPasswdEdit;
        
        private HtmlInputButton mUISigninButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICredentialsInputPanePane : HtmlDiv
    {
        
        public UICredentialsInputPanePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "CredentialsInputPane";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign in\r\n\r\n\r\nUse your Microsoft account.";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "container";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"container\" id=\"CredentialsInputPane\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
            this.WindowTitles.Add("Sign in to your Microsoft account");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIEmailorphonePane
        {
            get
            {
                if ((this.mUIEmailorphonePane == null))
                {
                    this.mUIEmailorphonePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIEmailorphonePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIEmailorphonePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIEmailorphonePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Email or phone";
                    this.mUIEmailorphonePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIEmailorphonePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "has-focus placeholder";
                    this.mUIEmailorphonePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"has-focus placeholder\" aria-hidden=\"true\" style=\"cursor: text;\" data-bind=" +
                        "\"text: hintText, css: hintCss\"";
                    this.mUIEmailorphonePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "35";
                    this.mUIEmailorphonePane.WindowTitles.Add("Sign in to your Microsoft account");
                    #endregion
                }
                return this.mUIEmailorphonePane;
            }
        }
        
        public HtmlDiv UIPasswordPane
        {
            get
            {
                if ((this.mUIPasswordPane == null))
                {
                    this.mUIPasswordPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIPasswordPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIPasswordPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIPasswordPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Password";
                    this.mUIPasswordPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIPasswordPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "placeholder";
                    this.mUIPasswordPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"placeholder\" aria-hidden=\"true\" style=\"cursor: text;\" data-bind=\"text: hin" +
                        "tText, css: hintCss\"";
                    this.mUIPasswordPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "42";
                    this.mUIPasswordPane.WindowTitles.Add("Sign in to your Microsoft account");
                    #endregion
                }
                return this.mUIPasswordPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIEmailorphonePane;
        
        private HtmlDiv mUIPasswordPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMicrosoftDynamicsSelDocument : HtmlDocument
    {
        
        public UIMicrosoftDynamicsSelDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Microsoft Dynamics - Select Profile";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/UserInfo/SelectProfile.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx?appe" +
                "ndSecurityAccountGuid=true&MNPVisible=false&ExcludedGroup=cust&ReturnUrl=https%3" +
                "A%2F%2Fbusinesscenter-pne.mbs.microsoft.com%2F%23%2F";
            this.WindowTitles.Add("Microsoft Dynamics - Select Profile");
            #endregion
        }
        
        #region Properties
        public HtmlRadioButton UIZero2TenInc010535421RadioButton
        {
            get
            {
                if ((this.mUIZero2TenInc010535421RadioButton == null))
                {
                    this.mUIZero2TenInc010535421RadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIZero2TenInc010535421RadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "2562063";
                    this.mUIZero2TenInc010535421RadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "radioGroup";
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "2562063";
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = "Zero2Ten, Inc. - 0105354218, Acct#5354218, raj@Zero2Ten inc";
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "7";
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = null;
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"radioGroup\" id=\"2562063\" onclick=\"";
                    this.mUIZero2TenInc010535421RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "11";
                    this.mUIZero2TenInc010535421RadioButton.WindowTitles.Add("Microsoft Dynamics - Select Profile");
                    #endregion
                }
                return this.mUIZero2TenInc010535421RadioButton;
            }
        }
        
        public HtmlInputButton UIContinueButton
        {
            get
            {
                if ((this.mUIContinueButton == null))
                {
                    this.mUIContinueButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIContinueButton.SearchProperties[HtmlButton.PropertyNames.Id] = "continueButton";
                    this.mUIContinueButton.SearchProperties[HtmlButton.PropertyNames.Name] = "continueButton";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Continue";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.Class] = "Paragraph";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"continueButton\" class=\"Paragraph\" ";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "12";
                    this.mUIContinueButton.WindowTitles.Add("Microsoft Dynamics - Select Profile");
                    #endregion
                }
                return this.mUIContinueButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlRadioButton mUIZero2TenInc010535421RadioButton;
        
        private HtmlInputButton mUIContinueButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHomeWelcometoPartnerDocument : HtmlDocument
    {
        
        public UIHomeWelcometoPartnerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home | Welcome to PartnerSource Business Center";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://businesscenter-pne.mbs.microsoft.com/#";
            this.WindowTitles.Add("Home | Welcome to PartnerSource Business Center");
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public UIAreanavigationbarCustom UIAreanavigationbarCustom
        {
            get
            {
                if ((this.mUIAreanavigationbarCustom == null))
                {
                    this.mUIAreanavigationbarCustom = new UIAreanavigationbarCustom(this);
                }
                return this.mUIAreanavigationbarCustom;
            }
        }
        
        public UIIframeplateFrame UIIframeplateFrame
        {
            get
            {
                if ((this.mUIIframeplateFrame == null))
                {
                    this.mUIIframeplateFrame = new UIIframeplateFrame(this);
                }
                return this.mUIIframeplateFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIAreanavigationbarCustom mUIAreanavigationbarCustom;
        
        private UIIframeplateFrame mUIIframeplateFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAreanavigationbarCustom : HtmlCustom
    {
        
        public UIAreanavigationbarCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "area-navigationbar";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "nav navbar-nav";
            this.FilterProperties["ControlDefinition"] = "class=\"nav navbar-nav\" id=\"area-navigati";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("Home | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIPartnerFocusHyperlink
        {
            get
            {
                if ((this.mUIPartnerFocusHyperlink == null))
                {
                    this.mUIPartnerFocusHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIPartnerFocusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIPartnerFocusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPartnerFocusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPartnerFocusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Partner Focus";
                    this.mUIPartnerFocusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIPartnerFocusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPartnerFocusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://businesscenter-pne.mbs.microsoft.com/#";
                    this.mUIPartnerFocusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "dropdown-toggle area-navigationbar-header";
                    this.mUIPartnerFocusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle area-navigationba";
                    this.mUIPartnerFocusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIPartnerFocusHyperlink.WindowTitles.Add("Home | Welcome to PartnerSource Business Center");
                    #endregion
                }
                return this.mUIPartnerFocusHyperlink;
            }
        }
        
        public HtmlHyperlink UIOrganizationMappingsHyperlink
        {
            get
            {
                if ((this.mUIOrganizationMappingsHyperlink == null))
                {
                    this.mUIOrganizationMappingsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIOrganizationMappingsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIOrganizationMappingsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIOrganizationMappingsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIOrganizationMappingsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Organization Mappings";
                    this.mUIOrganizationMappingsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIOrganizationMappingsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIOrganizationMappingsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://businesscenter-pne.mbs.microsoft.com/#embed/OrganizationMapping?t=1461137" +
                        "491536";
                    this.mUIOrganizationMappingsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIOrganizationMappingsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"https://businesscenter-pne.mbs.mic";
                    this.mUIOrganizationMappingsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "16";
                    this.mUIOrganizationMappingsHyperlink.WindowTitles.Add("Home | Welcome to PartnerSource Business Center");
                    #endregion
                }
                return this.mUIOrganizationMappingsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIPartnerFocusHyperlink;
        
        private HtmlHyperlink mUIOrganizationMappingsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIIframeplateFrame : HtmlIFrame
    {
        
        public UIIframeplateFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "iframeplate";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/MSVoice/OrganizationMapping.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                "?e=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=\"iframeplate\" src=\"https://mbs2-pne.p";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public UIOrganizationMappingDocument UIOrganizationMappingDocument
        {
            get
            {
                if ((this.mUIOrganizationMappingDocument == null))
                {
                    this.mUIOrganizationMappingDocument = new UIOrganizationMappingDocument(this);
                }
                return this.mUIOrganizationMappingDocument;
            }
        }
        
        public UIBankingandTaxEnrollmDocument UIBankingandTaxEnrollmDocument
        {
            get
            {
                if ((this.mUIBankingandTaxEnrollmDocument == null))
                {
                    this.mUIBankingandTaxEnrollmDocument = new UIBankingandTaxEnrollmDocument(this);
                }
                return this.mUIBankingandTaxEnrollmDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOrganizationMappingDocument mUIOrganizationMappingDocument;
        
        private UIBankingandTaxEnrollmDocument mUIBankingandTaxEnrollmDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOrganizationMappingDocument : HtmlDocument
    {
        
        public UIOrganizationMappingDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Organization Mapping";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MSVoice/OrganizationMapping.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                "?e=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK";
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem2382250Hyperlink
        {
            get
            {
                if ((this.mUIItem2382250Hyperlink == null))
                {
                    this.mUIItem2382250Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem2382250Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "bankingMappingPanel_contentTemplate_bankingMappingDataGrid__ctl2_BankingMapping_E" +
                        "xternalKeyLink";
                    this.mUIItem2382250Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem2382250Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem2382250Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "2382250";
                    this.mUIItem2382250Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/MSVoice/OrganizationMappingBankDetails.aspx";
                    this.mUIItem2382250Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem2382250Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                        "etails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYW" +
                        "PSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM";
                    this.mUIItem2382250Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIItem2382250Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"bankingMappingPanel_contentTemplate_";
                    this.mUIItem2382250Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "12";
                    this.mUIItem2382250Hyperlink.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
                    #endregion
                }
                return this.mUIItem2382250Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem2382250Hyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBankingandTaxEnrollmDocument : HtmlDocument
    {
        
        public UIBankingandTaxEnrollmDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Banking and Tax Enrollment";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MSVoice/OrganizationMappingBankDetails.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                "etails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYW" +
                "PSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM";
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIManageTaxProfileHyperlink
        {
            get
            {
                if ((this.mUIManageTaxProfileHyperlink == null))
                {
                    this.mUIManageTaxProfileHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIManageTaxProfileHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "taxProfileMappingPanel_headerTemplate_ManageTaxProfileLink";
                    this.mUIManageTaxProfileHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIManageTaxProfileHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIManageTaxProfileHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Manage Tax Profile";
                    this.mUIManageTaxProfileHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "__doPostBack(\'taxProfileMappingPanel$headerTemplate$ManageTaxProfileLink\',\'\')";
                    this.mUIManageTaxProfileHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIManageTaxProfileHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:__doPostBack(\'taxProfileMappingPanel$headerTemplate$ManageTaxProfileLi" +
                        "nk\',\'\')";
                    this.mUIManageTaxProfileHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIManageTaxProfileHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"taxProfileMappingPanel_headerTemplat";
                    this.mUIManageTaxProfileHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIManageTaxProfileHyperlink.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
                    #endregion
                }
                return this.mUIManageTaxProfileHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIManageTaxProfileHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILocationprofilesMicrDocument : HtmlDocument
    {
        
        public UILocationprofilesMicrDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Location profiles - Microsoft Partners Payee Portal";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/Locations/2382249/b1040434-30bb-40f0-a498-c3338d73845c";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://partnerpayeeportal-int.azurewebsites.net/Home/Locations/2382249/b1040434-" +
                "30bb-40f0-a498-c3338d73845c";
            this.WindowTitles.Add("Location profiles - Microsoft Partners Payee Portal");
            #endregion
        }
        
        #region Properties
        public UIBackPane UIBackPane
        {
            get
            {
                if ((this.mUIBackPane == null))
                {
                    this.mUIBackPane = new UIBackPane(this);
                }
                return this.mUIBackPane;
            }
        }
        #endregion
        
        #region Fields
        private UIBackPane mUIBackPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBackPane : HtmlDiv
    {
        
        public UIBackPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "AssociationsViewBreadCrumb";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Back";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "floatLeft";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"floatLeft\" id=\"AssociationsViewBreadCrumb\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
            this.WindowTitles.Add("Location profiles - Microsoft Partners Payee Portal");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBackHyperlink
        {
            get
            {
                if ((this.mUIBackHyperlink == null))
                {
                    this.mUIBackHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBackHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBackHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBackHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBackHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Back";
                    this.mUIBackHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIBackHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBackHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://businesscenter-pne.mbs.microsoft.com/#embed/OrganizationMapping";
                    this.mUIBackHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBackHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"https://businesscenter-pne.mbs.mic";
                    this.mUIBackHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIBackHyperlink.WindowTitles.Add("Location profiles - Microsoft Partners Payee Portal");
                    #endregion
                }
                return this.mUIBackHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBackHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIEmbedWelcometoPartneDocument : HtmlDocument
    {
        
        public UIEmbedWelcometoPartneDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Embed | Welcome to PartnerSource Business Center";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://businesscenter-pne.mbs.microsoft.com/#embed/OrganizationMapping";
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRajZero2TenHyperlink
        {
            get
            {
                if ((this.mUIRajZero2TenHyperlink == null))
                {
                    this.mUIRajZero2TenHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRajZero2TenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "customerName";
                    this.mUIRajZero2TenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRajZero2TenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRajZero2TenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "raj@Zero2Ten ";
                    this.mUIRajZero2TenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIRajZero2TenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRajZero2TenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://businesscenter-pne.mbs.microsoft.com/#";
                    this.mUIRajZero2TenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "flyout-header";
                    this.mUIRajZero2TenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"flyout-header\" id=\"customerName\" ";
                    this.mUIRajZero2TenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "10";
                    this.mUIRajZero2TenHyperlink.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
                    #endregion
                }
                return this.mUIRajZero2TenHyperlink;
            }
        }
        
        public UIGlobalNavigationmenuPane UIGlobalNavigationmenuPane
        {
            get
            {
                if ((this.mUIGlobalNavigationmenuPane == null))
                {
                    this.mUIGlobalNavigationmenuPane = new UIGlobalNavigationmenuPane(this);
                }
                return this.mUIGlobalNavigationmenuPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRajZero2TenHyperlink;
        
        private UIGlobalNavigationmenuPane mUIGlobalNavigationmenuPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGlobalNavigationmenuPane : HtmlDiv
    {
        
        public UIGlobalNavigationmenuPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "globalNavigation-menu-user";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "raj@Zero2Ten  \r\nManage my Profile\r\n\r\n\r\nM";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "btn-group globalNavigation-menu-header";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"btn-group globalNavigation-menu-header\" id=\"globalNavigation-menu-user\" da" +
                "ta-view=\"views/profileFlyoutMenu\" data-active-view=\"true\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "38";
            this.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISignOutHyperlink
        {
            get
            {
                if ((this.mUISignOutHyperlink == null))
                {
                    this.mUISignOutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISignOutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sign Out";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://businesscenter-pne.mbs.microsoft.com/#logout";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"https://businesscenter-pne.mbs.mic";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUISignOutHyperlink.WindowTitles.Add("Embed | Welcome to PartnerSource Business Center");
                    #endregion
                }
                return this.mUISignOutHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISignOutHyperlink;
        #endregion
    }
}
