//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTWebAndLoadTest {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    
    
    public class WebTest2Coded : WebTest {
        
        public WebTest2Coded() {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/");
            request1.ThinkTime = 7;
            WebTestRequest request1Dependent1 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/content/Configuration.PNE.xml");
            request1Dependent1.ThinkTime = 2;
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Content-Type", "text/xml"));
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Accept", "application/xml, text/xml, */*; q=0.01"));
            request1Dependent1.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1Dependent1.QueryStringParameters.Add("_", "1461063142402", false, false);
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/shell.json");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent2.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/translation.json");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent3.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/customersearch.js" +
                    "on");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent4.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/translation.json");
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent5.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent5);
            WebTestRequest request1Dependent6 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/partnersearch.jso" +
                    "n");
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent6);
            WebTestRequest request1Dependent7 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/EPOR.json");
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent7.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent7);
            WebTestRequest request1Dependent8 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/claimsummary.json" +
                    "");
            request1Dependent8.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent8.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent8);
            WebTestRequest request1Dependent9 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/ContractRenewal.j" +
                    "son");
            request1Dependent9.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent9.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request1.DependentRequests.Add(request1Dependent9);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/AuthenticationToken.asp" +
                    "x");
            request2.ExpectedResponseUrl = @"https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.partners.extranet.microsoft.com&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fAuthenticationToken.aspx%253fresponse_type%253dtoken%2526redirect_uri%253dhttps%25253A%25252F%25252Fbusinesscenter-pne.mbs.microsoft.com%25252F%252523trust%25252Fsignin&wct=2016-04-19T10%3a52%3a27Z";
            request2.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request2.QueryStringParameters.Add("response_type", "token", false, false);
            request2.QueryStringParameters.Add("redirect_uri", "https%3A%2F%2Fbusinesscenter-pne.mbs.microsoft.com%2F%23trust%2Fsignin", false, false);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            ExtractText extractionRule2 = new ExtractText();
            extractionRule2.StartsWith = "&amp;wct=";
            extractionRule2.EndsWith = "\"";
            extractionRule2.Index = 0;
            extractionRule2.IgnoreCase = false;
            extractionRule2.UseRegularExpression = false;
            extractionRule2.HtmlDecode = true;
            extractionRule2.Required = false;
            extractionRule2.ContextParameterName = "QueryStringParam40.wct";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://corp.sts.microsoft.com/adfs/ls/");
            request3.Method = "POST";
            request3.ExpectedResponseUrl = "https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp.sts.micr" +
                "osoft.com&wctx=e3ad223e-6e78-4d34-8744-8b26d78ded4d&wct=2016-04-19T10%3a52%3a27Z" +
                "";
            request3.Headers.Add(new WebTestRequestHeader("Referer", @"https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.partners.extranet.microsoft.com&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fAuthenticationToken.aspx%253fresponse_type%253dtoken%2526redirect_uri%253dhttps%25253A%25252F%25252Fbusinesscenter-pne.mbs.microsoft.com%25252F%252523trust%25252Fsignin&wct=2016-04-19T10%3a52%3a27Z"));
            request3.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            request3.QueryStringParameters.Add("wtrealm", "urn%3ambs2-pne.partners.extranet.microsoft.com", false, false);
            request3.QueryStringParameters.Add("wctx", "rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fAuthenticationToken.aspx%253frespo" +
                    "nse_type%253dtoken%2526redirect_uri%253dhttps%25253A%25252F%25252Fbusinesscenter" +
                    "-pne.mbs.microsoft.com%25252F%252523trust%25252Fsignin", false, false);
            request3.QueryStringParameters.Add("wct", this.Context["QueryStringParam40.wct"].ToString(), false, false);
            FormPostHttpBody request3Body = new FormPostHttpBody();
            request3Body.FormPostParameters.Add("__EVENTTARGET", "CustomHRD$LinkButton_LiveId");
            request3Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request3Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request3Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request3Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request3Body.FormPostParameters.Add("__db", this.Context["$HIDDEN1.__db"].ToString());
            request3Body.FormPostParameters.Add("CustomHRD$emailTB", "alias@fabrikam.com");
            request3.Body = request3Body;
            ExtractHiddenFields extractionRule3 = new ExtractHiddenFields();
            extractionRule3.Required = true;
            extractionRule3.HtmlDecode = true;
            extractionRule3.ContextParameterName = "1";
            request3.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            ExtractText extractionRule4 = new ExtractText();
            extractionRule4.StartsWith = "&wctx=";
            extractionRule4.EndsWith = "&";
            extractionRule4.Index = 4;
            extractionRule4.IgnoreCase = false;
            extractionRule4.UseRegularExpression = false;
            extractionRule4.HtmlDecode = true;
            extractionRule4.Required = false;
            extractionRule4.ContextParameterName = "QueryStringParam32.wctx";
            request3.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule4.Extract);
            ExtractText extractionRule5 = new ExtractText();
            extractionRule5.StartsWith = "&wct=";
            extractionRule5.EndsWith = "&";
            extractionRule5.Index = 3;
            extractionRule5.IgnoreCase = false;
            extractionRule5.UseRegularExpression = false;
            extractionRule5.HtmlDecode = true;
            extractionRule5.Required = false;
            extractionRule5.ContextParameterName = "QueryStringParam33.wct";
            request3.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule5.Extract);
            ExtractText extractionRule6 = new ExtractText();
            extractionRule6.StartsWith = "&bk=";
            extractionRule6.EndsWith = "&";
            extractionRule6.Index = 3;
            extractionRule6.IgnoreCase = false;
            extractionRule6.UseRegularExpression = false;
            extractionRule6.HtmlDecode = true;
            extractionRule6.Required = false;
            extractionRule6.ContextParameterName = "QueryStringParam34.bk";
            request3.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule6.Extract);
            ExtractText extractionRule7 = new ExtractText();
            extractionRule7.StartsWith = "&uaid=";
            extractionRule7.EndsWith = "&";
            extractionRule7.Index = 0;
            extractionRule7.IgnoreCase = false;
            extractionRule7.UseRegularExpression = false;
            extractionRule7.HtmlDecode = true;
            extractionRule7.Required = false;
            extractionRule7.ContextParameterName = "QueryStringParam35.uaid";
            request3.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule7.Extract);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://login.live.com/ppsecure/post.srf");
            request4.Method = "POST";
            request4.Headers.Add(new WebTestRequestHeader("Referer", "https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp.sts.micr" +
                        "osoft.com&wctx=e3ad223e-6e78-4d34-8744-8b26d78ded4d&wct=2016-04-19T10%3a52%3a27Z" +
                        ""));
            request4.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            request4.QueryStringParameters.Add("wtrealm", "http%3a%2f%2fcorp.sts.microsoft.com", false, false);
            request4.QueryStringParameters.Add("wctx", this.Context["QueryStringParam32.wctx"].ToString(), false, false);
            request4.QueryStringParameters.Add("wct", this.Context["QueryStringParam33.wct"].ToString(), false, false);
            request4.QueryStringParameters.Add("bk", this.Context["QueryStringParam34.bk"].ToString(), false, false);
            request4.QueryStringParameters.Add("uaid", this.Context["QueryStringParam35.uaid"].ToString(), false, false);
            request4.QueryStringParameters.Add("pid", "0", false, false);
            FormPostHttpBody request4Body = new FormPostHttpBody();
            request4Body.FormPostParameters.Add("loginfmt", "px3rajesh@outlook.com");
            request4Body.FormPostParameters.Add("login", "px3rajesh@outlook.com");
            request4Body.FormPostParameters.Add("passwd", "rajeshpx3");
            request4Body.FormPostParameters.Add("type", "11");
            request4Body.FormPostParameters.Add("PPFT", this.Context["$HIDDEN1.PPFT"].ToString());
            request4Body.FormPostParameters.Add("PPSX", "Passpo");
            request4Body.FormPostParameters.Add("NewUser", "1");
            request4Body.FormPostParameters.Add("LoginOptions", "3");
            request4Body.FormPostParameters.Add("FoundMSAs", "");
            request4Body.FormPostParameters.Add("fspost", "0");
            request4Body.FormPostParameters.Add("i2", "1");
            request4Body.FormPostParameters.Add("i16", @"{""navigationStart"":1461063155145,""unloadEventStart"":0,""unloadEventEnd"":0,""redirectStart"":0,""redirectEnd"":0,""fetchStart"":1461063155440,""domainLookupStart"":1461063155440,""domainLookupEnd"":1461063155440,""connectStart"":1461063155440,""connectEnd"":1461063155440,""requestStart"":1461063156738,""responseStart"":1461063157032,""responseEnd"":1461063157035,""domLoading"":1461063157032,""domInteractive"":1461063157235,""domContentLoadedEventStart"":1461063157235,""domContentLoadedEventEnd"":1461063157235,""domComplete"":1461063157236,""loadEventStart"":1461063157238,""loadEventEnd"":0,""msFirstPaint"":0}");
            request4Body.FormPostParameters.Add("i17", "0");
            request4Body.FormPostParameters.Add("i18", "__DefaultLogin_Strings|1,__DefaultLogin_Core|1,");
            request4Body.FormPostParameters.Add("i19", "6690");
            request4Body.FormPostParameters.Add("i21", "0");
            request4Body.FormPostParameters.Add("i22", "0");
            request4Body.FormPostParameters.Add("i13", "0");
            request4.Body = request4Body;
            ExtractHiddenFields extractionRule8 = new ExtractHiddenFields();
            extractionRule8.Required = true;
            extractionRule8.HtmlDecode = true;
            extractionRule8.ContextParameterName = "1";
            request4.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule8.Extract);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://corp.sts.microsoft.com/adfs/ls/");
            request5.Method = "POST";
            request5.Headers.Add(new WebTestRequestHeader("Referer", "https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp." +
                        "sts.microsoft.com&wctx=e3ad223e-6e78-4d34-8744-8b26d78ded4d&wct=2016-04-19T10%3a" +
                        "52%3a27Z&bk=1461063156&uaid=5aa0f13f13f44171822863007d3242c8&pid=0"));
            FormPostHttpBody request5Body = new FormPostHttpBody();
            request5Body.FormPostParameters.Add("wctx", this.Context["$HIDDEN1.wctx"].ToString());
            request5Body.FormPostParameters.Add("NAP", this.Context["$HIDDEN1.NAP"].ToString());
            request5Body.FormPostParameters.Add("wresult", this.Context["$HIDDEN1.wresult"].ToString());
            request5Body.FormPostParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString());
            request5Body.FormPostParameters.Add("ANON", this.Context["$HIDDEN1.ANON"].ToString());
            request5.Body = request5Body;
            ExtractHiddenFields extractionRule9 = new ExtractHiddenFields();
            extractionRule9.Required = true;
            extractionRule9.HtmlDecode = true;
            extractionRule9.ContextParameterName = "1";
            request5.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule9.Extract);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/");
            request6.Method = "POST";
            request6.ExpectedResponseUrl = @"https://businesscenter-pne.mbs.microsoft.com/#trust/signin?authenticationToken=eyJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiZXhwaXJlc19pbiI6IjM2MDAiLCJleHBpcmVzX29uIjoiMTQ2MTA2Njc2OCIsImFjY2Vzc190b2tlbiI6ImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSlNVekkxTmlJc0luZzFkQ0k2SWtkS1ZEWlBRM1JMUW5oTGVGcEpWWEEyTkcwdFZFcFViekpqWnlKOS5leUpwYzNNaU9pSk5RbE11U1ZRaUxDSmhkV1FpT2lKRmJHVmpkSEp2Ym1salVISnZabWxzWlNJc0ltNWlaaUk2TVRRMk1UQTJNekUyT0N3aVpYaHdJam94TkRZeE1EWTJOelk0TENKb2RIUndPaTh2YzJOb1pXMWhjeTU0Yld4emIyRndMbTl5Wnk5amJHRnBiWE12VUZWSlJDSTZJakF3TUROQ1JrWkVSVEV6TlRCRU16QWlMQ0pvZEhSd09pOHZjM1J6TG0xelpuUXVibVYwTDNWelpYSXZRV1JtYzFCUVNVUWlPaUkzTnpJek9EUkJOa1F5UmpSQk1Ea3dSRVV4T0RoR1JUSTRNMFEzTnpFNVJqWXlPVGs1T1RZMVFrSkJNekF3UVRReU9URkRSREZDTnpZNU5rTTFRVEJFSW4wLmZhZmpUN2tmRW9pcW5aQldLYzZ5NlhyV2FFQ2xYNlhQUTZiMms4OXpNcVFIZURLVlo5QmpQT1luTEFmcWNyekp1YUZIWFJhbUQ1UXFxWktNd0NkS0pwTE1qSlJ4VmZHcVgyeE5qNU4wdXdTYXBGQXhpRG9HWDM1RHNrVUdCaXc0X29jay0zYUZWM2cwMFo1d05VU01wNTFfaDNRZ1pHUDN2Q0tVMWM5S3hQQ3BLRXRZdDBvdW5mRmdzNnR2djRzUmxkaWhDM1NFSEo3aDRoNjdMMEQ2N3JJXzhIWmRBRmdjVmRxMGFVeFl2R24tdzRrRFZrRWxmWDZkZ3JwZmVGSEI2dVNFX3oybTBncVpCSVdmSFdRRkdpVmVXVjdPUXdwRUdocmFCMzVjRW44Znc4Q2lmRGdKbEY5a0tMc01lSDVtS0cyclp6ZDVGOURXZDc3VVdWV3Z6ZyJ9";
            request6.Headers.Add(new WebTestRequestHeader("Referer", "https://corp.sts.microsoft.com/adfs/ls/"));
            FormPostHttpBody request6Body = new FormPostHttpBody();
            request6Body.FormPostParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString());
            request6Body.FormPostParameters.Add("wresult", this.Context["$HIDDEN1.wresult"].ToString());
            request6Body.FormPostParameters.Add("wctx", this.Context["$HIDDEN1.wctx"].ToString());
            request6.Body = request6Body;
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/");
            request7.ThinkTime = 7;
            request7.ExpectedResponseUrl = "https://businesscenter-pne.mbs.microsoft.com/#";
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx");
            request8.Method = "POST";
            request8.ExpectedResponseUrl = "https://businesscenter-pne.mbs.microsoft.com/#/?SecurityAccountGuid=62b79819-5941" +
                "-4a73-bdd4-cdafd7a22844";
            request8.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx?appe" +
                        "ndSecurityAccountGuid=true&MNPVisible=false&ExcludedGroup=cust&ReturnUrl=https%3" +
                        "A%2F%2Fbusinesscenter-pne.mbs.microsoft.com%2F%23%2F"));
            request8.QueryStringParameters.Add("appendSecurityAccountGuid", "true", false, false);
            request8.QueryStringParameters.Add("MNPVisible", "false", false, false);
            request8.QueryStringParameters.Add("ExcludedGroup", "cust", false, false);
            request8.QueryStringParameters.Add("ReturnUrl", "https%3a%2f%2fbusinesscenter-pne.mbs.microsoft.com%2f%23%2f", false, false);
            FormPostHttpBody request8Body = new FormPostHttpBody();
            request8Body.FormPostParameters.Add("hiddenNetworkDomainGroupID", "2");
            request8Body.FormPostParameters.Add("__VIEWSTATE", @"/wEPDwULLTE5MTk5NzkwMjIPZBYKAgEPFgIeBFRleHQFI01pY3Jvc29mdCBEeW5hbWljcyAtIFNlbGVjdCBQcm9maWxlZAIDDxYCHgdWaXNpYmxlaBYCZg9kFgICAw8PFgIfAGVkZAIFDxYCHwFoZAIHD2QWBAIBDxYCHwAFPDxhIGlkPWxvZ2lub3V0TGluayBocmVmPScvVXNlckluZm8vTG9nb3V0LmFzcHgnPlNpZ24gT3V0PC9hPmQCCQ8PFgQfAAUIQ29udGludWUeB0VuYWJsZWRoZGQCCQ8WAh8BaGQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFg4FBzI1NjIwOTMFBzI1NjIwOTMFBzI1NjIwNTgFBzI1NjIwNTgFBzI1NjIwNjQFBzI1NjIwNjQFBzI1NjIwOTIFBzI1NjIwOTIFBzI1NjIwNTcFBzI1NjIwNTcFBzI1NjIwNjEFBzI1NjIwNjEFBzI1NjIwNjMFBzI1NjIwNjN9HFERXrZXKJZkY63Ydzwy8FztNQ==");
            request8Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", "D1C42006");
            request8Body.FormPostParameters.Add("__EVENTVALIDATION", "/wEdAAl9kcVN2OGt2stVVPyJh/H4XQleWhopYjXV0GVb5U9rZtxLggun4lDNuV2Y5gRg4Ca14GXVQGCTM" +
                    "j79kJjF674EJwHV3hjglF7TDpJww94O7u1di4LpLr9vh3ahB6e4xp1A8lQ68WzYfkQy37DaIhzwDh7eE" +
                    "kCvwST81bvSxcO6lAzbLIHFAKFO0Oxc+eQifFg6RKJxCQ/ZPJ42Em/i8Q+KM04PvA==");
            request8Body.FormPostParameters.Add("radioGroup", "2562063");
            request8Body.FormPostParameters.Add("continueButton", "Continue");
            request8.Body = request8Body;
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/VOICE/Startup.aspx");
            request9.ExpectedResponseUrl = "https://businesscenter-pne.mbs.microsoft.com/#/?VoiceContextSet=true";
            request9.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request9.QueryStringParameters.Add("appendVoiceContextSet", "true", false, false);
            request9.QueryStringParameters.Add("ReturnUrl", "https%3A%2F%2Fbusinesscenter-pne.mbs.microsoft.com%2F%23%2F", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/");
            request10.ExpectedResponseUrl = "https://businesscenter-pne.mbs.microsoft.com/#";
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/shell.html");
            request11.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request11.QueryStringParameters.Add("v", "26201", false, false);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request12.Method = "POST";
            request12.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            StringHttpBody request12Body = new StringHttpBody();
            request12Body.ContentType = "application/json";
            request12Body.InsertByteOrderMark = false;
            request12Body.BodyString = "[{\"time\":\"2016-04-19T10:52:25.410Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\"" +
                ",\"name\":\"Microsoft.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDe" +
                "pendency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device" +
                ".id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0" +
                ".22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"d" +
                "ata\":{\"baseType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"O8f3P\",\"ver\":2,\"name\":" +
                "\"https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en-IN/translation." +
                "json\",\"kind\":1,\"value\":231.33695273292596,\"dependencyKind\":1,\"success\":false,\"de" +
                "pendencySource\":2,\"commandName\":\"cdn/app/locales/en-IN/translation.json\",\"depend" +
                "encyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"404\"}}},{\"time\":\"2016-04-19T1" +
                "0:52:25.468Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsoft.Ap" +
                "plicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":{\"ai" +
                ".session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"ai.de" +
                "vice.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"" +
                "1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":\"Rem" +
                "oteDependencyData\",\"baseData\":{\"id\":\"C0IlW\",\"ver\":2,\"name\":\"https://businesscent" +
                "er-pne.mbs.microsoft.com/cdn/app/locales/en/translation.json\",\"kind\":1,\"value\":2" +
                "83.35967023540615,\"dependencyKind\":1,\"success\":true,\"dependencySource\":2,\"comman" +
                "dName\":\"cdn/app/locales/en/translation.json\",\"dependencyTypeName\":\"Ajax\",\"proper" +
                "ties\":{},\"resultCode\":\"200\"}}},{\"time\":\"2016-04-19T10:52:25.480Z\",\"iKey\":\"b08306" +
                "11-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611bc" +
                "d0443aae45abfe84246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.ses" +
                "sion.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.int" +
                "ernal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeA" +
                "A9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseData" +
                "\":{\"id\":\"V5oN7\",\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.com/cdn" +
                "/app/locales/en/shell.json\",\"kind\":1,\"value\":281.8603813909749,\"dependencyKind\":" +
                "1,\"success\":true,\"dependencySource\":2,\"commandName\":\"cdn/app/locales/en/shell.js" +
                "on\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"200\"}}},{\"time\":\"2" +
                "016-04-19T10:52:25.491Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"M" +
                "icrosoft.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\"," +
                "\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"brow" +
                "ser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai" +
                ".user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"bas" +
                "eType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"1Uclh\",\"ver\":2,\"name\":\"https://b" +
                "usinesscenter-pne.mbs.microsoft.com/cdn/app/locales/en-IN/shell.json\",\"kind\":1,\"" +
                "value\":297.1110464586118,\"dependencyKind\":1,\"success\":false,\"dependencySource\":2" +
                ",\"commandName\":\"cdn/app/locales/en-IN/shell.json\",\"dependencyTypeName\":\"Ajax\",\"p" +
                "roperties\":{},\"resultCode\":\"404\"}}},{\"time\":\"2016-04-19T10:52:25.503Z\",\"iKey\":\"b" +
                "0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830" +
                "611bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"a" +
                "i.session.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"a" +
                "i.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\"" +
                ":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"bas" +
                "eData\":{\"id\":\"39KqS\",\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.co" +
                "m/cdn/app/locales/en-IN/translation.json\",\"kind\":1,\"value\":301.09691256240603,\"d" +
                "ependencyKind\":1,\"success\":false,\"dependencySource\":2,\"commandName\":\"cdn/app/loc" +
                "ales/en-IN/translation.json\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"result" +
                "Code\":\"404\"}}},{\"time\":\"2016-04-19T10:52:25.512Z\",\"iKey\":\"b0830611-bcd0-443a-ae4" +
                "5-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611bcd0443aae45abfe84" +
                "246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"t" +
                "rue\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion" +
                "\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operatio" +
                "n.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"Qz0nw\"," +
                "\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/" +
                "translation.json\",\"kind\":1,\"value\":306.7569450667361,\"dependencyKind\":1,\"success" +
                "\":true,\"dependencySource\":2,\"commandName\":\"cdn/app/locales/en/translation.json\"," +
                "\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"200\"}}},{\"time\":\"2016-" +
                "04-19T10:52:25.637Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Micro" +
                "soft.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\",\"tag" +
                "s\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"browser\"" +
                ",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.use" +
                "r.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseTyp" +
                "e\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"tWUnq\",\"ver\":2,\"name\":\"https://busin" +
                "esscenter-pne.mbs.microsoft.com/cdn/app/locales/en-IN/customersearch.json\",\"kind" +
                "\":1,\"value\":426.45846105382043,\"dependencyKind\":1,\"success\":false,\"dependencySou" +
                "rce\":2,\"commandName\":\"cdn/app/locales/en-IN/customersearch.json\",\"dependencyType" +
                "Name\":\"Ajax\",\"properties\":{},\"resultCode\":\"404\"}}},{\"time\":\"2016-04-19T10:52:25." +
                "692Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsoft.Applicatio" +
                "nInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":{\"ai.session" +
                ".id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"ai.device.typ" +
                "e\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"a" +
                "i.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDepen" +
                "dencyData\",\"baseData\":{\"id\":\"xhqqM\",\"ver\":2,\"name\":\"https://businesscenter-pne.m" +
                "bs.microsoft.com/cdn/app/locales/en-IN/partnersearch.json\",\"kind\":1,\"value\":471." +
                "4959452487192,\"dependencyKind\":1,\"success\":false,\"dependencySource\":2,\"commandNa" +
                "me\":\"cdn/app/locales/en-IN/partnersearch.json\",\"dependencyTypeName\":\"Ajax\",\"prop" +
                "erties\":{},\"resultCode\":\"404\"}}},{\"time\":\"2016-04-19T10:52:25.699Z\",\"iKey\":\"b083" +
                "0611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611" +
                "bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.s" +
                "ession.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.i" +
                "nternal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"G" +
                "eAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseDa" +
                "ta\":{\"id\":\"2BQpG\",\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.com/c" +
                "dn/app/locales/en-IN/claimsummary.json\",\"kind\":1,\"value\":469.68479800852765,\"dep" +
                "endencyKind\":1,\"success\":false,\"dependencySource\":2,\"commandName\":\"cdn/app/local" +
                "es/en-IN/claimsummary.json\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"resultC" +
                "ode\":\"404\"}}},{\"time\":\"2016-04-19T10:52:25.708Z\",\"iKey\":\"b0830611-bcd0-443a-ae45" +
                "-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611bcd0443aae45abfe842" +
                "46a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"tr" +
                "ue\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion\"" +
                ":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation" +
                ".name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"DPwa9\",\"" +
                "ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/c" +
                "ustomersearch.json\",\"kind\":1,\"value\":492.3861154326096,\"dependencyKind\":1,\"succe" +
                "ss\":true,\"dependencySource\":2,\"commandName\":\"cdn/app/locales/en/customersearch.j" +
                "son\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"200\"}}},{\"time\":\"" +
                "2016-04-19T10:52:25.715Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"" +
                "Microsoft.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\"" +
                ",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"bro" +
                "wser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"a" +
                "i.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"ba" +
                "seType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"Nnduv\",\"ver\":2,\"name\":\"https://" +
                "businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/partnersearch.json\",\"kin" +
                "d\":1,\"value\":489.7345295537152,\"dependencyKind\":1,\"success\":true,\"dependencySour" +
                "ce\":2,\"commandName\":\"cdn/app/locales/en/partnersearch.json\",\"dependencyTypeName\"" +
                ":\"Ajax\",\"properties\":{},\"resultCode\":\"200\"}}},{\"time\":\"2016-04-19T10:52:25.724Z\"" +
                ",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsi" +
                "ghts.b0830611bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":" +
                "\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"B" +
                "rowser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.ope" +
                "ration.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependency" +
                "Data\",\"baseData\":{\"id\":\"Y0tY8\",\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.mi" +
                "crosoft.com/cdn/app/locales/en/claimsummary.json\",\"kind\":1,\"value\":490.507069908" +
                "7828,\"dependencyKind\":1,\"success\":true,\"dependencySource\":2,\"commandName\":\"cdn/a" +
                "pp/locales/en/claimsummary.json\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"re" +
                "sultCode\":\"200\"}}},{\"time\":\"2016-04-19T10:52:25.865Z\",\"iKey\":\"b0830611-bcd0-443a" +
                "-ae45-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611bcd0443aae45ab" +
                "fe84246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst" +
                "\":\"true\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVer" +
                "sion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.oper" +
                "ation.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"C4W" +
                "nx\",\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales" +
                "/en-IN/EPOR.json\",\"kind\":1,\"value\":622.7472671927735,\"dependencyKind\":1,\"success" +
                "\":false,\"dependencySource\":2,\"commandName\":\"cdn/app/locales/en-IN/EPOR.json\",\"de" +
                "pendencyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"404\"}}},{\"time\":\"2016-04-" +
                "19T10:52:25.915Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsof" +
                "t.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":" +
                "{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"a" +
                "i.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.i" +
                "d\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":" +
                "\"RemoteDependencyData\",\"baseData\":{\"id\":\"x/byB\",\"ver\":2,\"name\":\"https://business" +
                "center-pne.mbs.microsoft.com/cdn/app/locales/en/EPOR.json\",\"kind\":1,\"value\":669." +
                "38549290009,\"dependencyKind\":1,\"success\":true,\"dependencySource\":2,\"commandName\"" +
                ":\"cdn/app/locales/en/EPOR.json\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"res" +
                "ultCode\":\"200\"}}},{\"time\":\"2016-04-19T10:52:25.925Z\",\"iKey\":\"b0830611-bcd0-443a-" +
                "ae45-abfe84246a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611bcd0443aae45abf" +
                "e84246a25.RemoteDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\"" +
                ":\"true\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVers" +
                "ion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.opera" +
                "tion.name\":\"/\"},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"u4yy" +
                "Z\",\"ver\":2,\"name\":\"https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/" +
                "en-IN/ContractRenewal.json\",\"kind\":1,\"value\":674.5899752921305,\"dependencyKind\":" +
                "1,\"success\":false,\"dependencySource\":2,\"commandName\":\"cdn/app/locales/en-IN/Cont" +
                "ractRenewal.json\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"404\"" +
                "}}},{\"time\":\"2016-04-19T10:52:25.929Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246" +
                "a25\",\"name\":\"Microsoft.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.Remo" +
                "teDependency\",\"tags\":{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.de" +
                "vice.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScri" +
                "pt:0.22.9\",\"ai.user.id\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"" +
                "},\"data\":{\"baseType\":\"RemoteDependencyData\",\"baseData\":{\"id\":\"dMJ0h\",\"ver\":2,\"na" +
                "me\":\"https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/ContractRen" +
                "ewal.json\",\"kind\":1,\"value\":675.5966068227508,\"dependencyKind\":1,\"success\":true," +
                "\"dependencySource\":2,\"commandName\":\"cdn/app/locales/en/ContractRenewal.json\",\"de" +
                "pendencyTypeName\":\"Ajax\",\"properties\":{},\"resultCode\":\"200\"}}},{\"time\":\"2016-04-" +
                "19T10:52:26.389Z\",\"iKey\":\"b0830611-bcd0-443a-ae45-abfe84246a25\",\"name\":\"Microsof" +
                "t.ApplicationInsights.b0830611bcd0443aae45abfe84246a25.RemoteDependency\",\"tags\":" +
                "{\"ai.session.id\":\"Tnf2m\",\"ai.session.isFirst\":\"true\",\"ai.device.id\":\"browser\",\"a" +
                "i.device.type\":\"Browser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.i" +
                "d\":\"1RPB\",\"ai.operation.id\":\"GeAA9\",\"ai.operation.name\":\"/\"},\"data\":{\"baseType\":" +
                "\"RemoteDependencyData\",\"baseData\":{\"id\":\"6sYlX\",\"ver\":2,\"name\":\"https://business" +
                "center-pne.mbs.microsoft.com/cdn/App/views/shell.html?v=26201\",\"kind\":1,\"value\":" +
                "235.554146710032,\"dependencyKind\":1,\"success\":true,\"dependencySource\":2,\"command" +
                "Name\":\"cdn/App/views/shell.html\",\"dependencyTypeName\":\"Ajax\",\"properties\":{},\"re" +
                "sultCode\":\"200\"}}}]";
            request12.Body = request12Body;
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/content/Configuration.PNE.xml");
            request13.Headers.Add(new WebTestRequestHeader("Content-Type", "text/xml"));
            request13.Headers.Add(new WebTestRequestHeader("Accept", "application/xml, text/xml, */*; q=0.01"));
            request13.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request13.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request13.QueryStringParameters.Add("_", "1461063168588", false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/translation.json");
            request14.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request14.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request14.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/shell.json");
            request15.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request15.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request15.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/translation.json");
            request16.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request16.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request16.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/customersearch.js" +
                    "on");
            request17.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request17.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request17.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/partnersearch.jso" +
                    "n");
            request18.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request18.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request18.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/claimsummary.json" +
                    "");
            request19.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request19.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request19.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/EPOR.json");
            request20.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request20.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request20.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/app/locales/en/ContractRenewal.j" +
                    "son");
            request21.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request21.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request21.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/shell.html");
            request22.ThinkTime = 1;
            request22.Headers.Add(new WebTestRequestHeader("Referer", @"https://businesscenter-pne.mbs.microsoft.com/#trust/signin?authenticationToken=eyJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiZXhwaXJlc19pbiI6IjM2MDAiLCJleHBpcmVzX29uIjoiMTQ2MTA2Njc2OCIsImFjY2Vzc190b2tlbiI6ImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSlNVekkxTmlJc0luZzFkQ0k2SWtkS1ZEWlBRM1JMUW5oTGVGcEpWWEEyTkcwdFZFcFViekpqWnlKOS5leUpwYzNNaU9pSk5RbE11U1ZRaUxDSmhkV1FpT2lKRmJHVmpkSEp2Ym1salVISnZabWxzWlNJc0ltNWlaaUk2TVRRMk1UQTJNekUyT0N3aVpYaHdJam94TkRZeE1EWTJOelk0TENKb2RIUndPaTh2YzJOb1pXMWhjeTU0Yld4emIyRndMbTl5Wnk5amJHRnBiWE12VUZWSlJDSTZJakF3TUROQ1JrWkVSVEV6TlRCRU16QWlMQ0pvZEhSd09pOHZjM1J6TG0xelpuUXVibVYwTDNWelpYSXZRV1JtYzFCUVNVUWlPaUkzTnpJek9EUkJOa1F5UmpSQk1Ea3dSRVV4T0RoR1JUSTRNMFEzTnpFNVJqWXlPVGs1T1RZMVFrSkJNekF3UVRReU9URkRSREZDTnpZNU5rTTFRVEJFSW4wLmZhZmpUN2tmRW9pcW5aQldLYzZ5NlhyV2FFQ2xYNlhQUTZiMms4OXpNcVFIZURLVlo5QmpQT1luTEFmcWNyekp1YUZIWFJhbUQ1UXFxWktNd0NkS0pwTE1qSlJ4VmZHcVgyeE5qNU4wdXdTYXBGQXhpRG9HWDM1RHNrVUdCaXc0X29jay0zYUZWM2cwMFo1d05VU01wNTFfaDNRZ1pHUDN2Q0tVMWM5S3hQQ3BLRXRZdDBvdW5mRmdzNnR2djRzUmxkaWhDM1NFSEo3aDRoNjdMMEQ2N3JJXzhIWmRBRmdjVmRxMGFVeFl2R24tdzRrRFZrRWxmWDZkZ3JwZmVGSEI2dVNFX3oybTBncVpCSVdmSFdRRkdpVmVXVjdPUXdwRUdocmFCMzVjRW44Znc4Q2lmRGdKbEY5a0tMc01lSDVtS0cyclp6ZDVGOURXZDc3VVdWV3Z6ZyJ9"));
            request22.QueryStringParameters.Add("v", "26201", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/header.html");
            request23.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request23.QueryStringParameters.Add("v", "26201", false, false);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/switchAccountFlyoutMen" +
                    "u.html");
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request24.QueryStringParameters.Add("v", "26201", false, false);
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/profileFlyoutMenu.html" +
                    "");
            request25.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request25.QueryStringParameters.Add("v", "26201", false, false);
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/firmListFlyoutMenu.htm" +
                    "l");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request26.QueryStringParameters.Add("v", "26201", false, false);
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/trust/signin.html");
            request27.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request27.QueryStringParameters.Add("v", "26201", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/footer.html");
            request28.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request28.QueryStringParameters.Add("v", "26201", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx");
            request29.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request29.QueryStringParameters.Add("appendSecurityAccountGuid", "true", false, false);
            request29.QueryStringParameters.Add("MNPVisible", "false", false, false);
            request29.QueryStringParameters.Add("ExcludedGroup", "cust", false, false);
            request29.QueryStringParameters.Add("ReturnUrl", "https%3A%2F%2Fbusinesscenter-pne.mbs.microsoft.com%2F%23%2F", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/library/mnp/2/aspx/js.aspx");
            request30.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx?appe" +
                        "ndSecurityAccountGuid=true&MNPVisible=false&ExcludedGroup=cust&ReturnUrl=https%3" +
                        "A%2F%2Fbusinesscenter-pne.mbs.microsoft.com%2F%23%2F"));
            request30.QueryStringParameters.Add("", "", false, false);
            request30.QueryStringParameters.Add("name", "Menu", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/content/Configuration.PNE.xml");
            request31.Headers.Add(new WebTestRequestHeader("Content-Type", "text/xml"));
            request31.Headers.Add(new WebTestRequestHeader("Accept", "application/xml, text/xml, */*; q=0.01"));
            request31.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request31.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request31.QueryStringParameters.Add("_", "1461063178454", false, false);
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/shell.html");
            request32.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#/?SecurityAccountGuid=62b79819-5941" +
                        "-4a73-bdd4-cdafd7a22844"));
            request32.QueryStringParameters.Add("v", "26201", false, false);
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/content/Configuration.PNE.xml");
            request33.Headers.Add(new WebTestRequestHeader("Content-Type", "text/xml"));
            request33.Headers.Add(new WebTestRequestHeader("Accept", "application/xml, text/xml, */*; q=0.01"));
            request33.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request33.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/"));
            request33.QueryStringParameters.Add("_", "1461063180902", false, false);
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/shell.html");
            request34.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#/?VoiceContextSet=true"));
            request34.QueryStringParameters.Add("v", "26201", false, false);
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("https://mbsidentity-pne.mbs.microsoft.com/odata/SecurityAccountInformation");
            request35.Method = "OPTIONS";
            request35.QueryStringParameters.Add("$expand", "SecurityGroups", false, false);
            StringHttpBody request35Body = new StringHttpBody();
            request35Body.ContentType = "";
            request35Body.InsertByteOrderMark = false;
            request35Body.BodyString = "";
            request35.Body = request35Body;
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("https://mbsidentity-pne.mbs.microsoft.com/odata/SecurityAccountInformation");
            request36.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request36.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#/?VoiceContextSet=true"));
            request36.QueryStringParameters.Add("$expand", "SecurityGroups", false, false);
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/home.html");
            request37.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request37.QueryStringParameters.Add("v", "26201", false, false);
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/header.html");
            request38.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request38.QueryStringParameters.Add("v", "26201", false, false);
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/footer.html");
            request39.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request39.QueryStringParameters.Add("v", "26201", false, false);
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/switchAccountFlyoutMen" +
                    "u.html");
            request40.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request40.QueryStringParameters.Add("v", "26201", false, false);
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/content/css/font/NGVLSymbols.eot" +
                    "");
            request41.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#/?VoiceContextSet=true"));
            request41.QueryStringParameters.Add("", "", false, false);
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/profileFlyoutMenu.html" +
                    "");
            request42.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request42.QueryStringParameters.Add("v", "26201", false, false);
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/navbar.html");
            request43.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request43.QueryStringParameters.Add("v", "26201", false, false);
            yield return request43;
            request43 = null;

            WebTestRequest request44 = new WebTestRequest("https://psbc-common-pne.mbs.microsoft.com/cdn/app/widgets/quicklink/view.html");
            request44.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request44.QueryStringParameters.Add("v", "26201", false, false);
            yield return request44;
            request44 = null;

            WebTestRequest request45 = new WebTestRequest("https://psbc-svc-navigation-pne.mbs.microsoft.com/api/navigation/GetNavigationCat" +
                    "alog");
            request45.Method = "OPTIONS";
            request45.QueryStringParameters.Add("securityAccountGUID", "62b79819-5941-4a73-bdd4-cdafd7a22844", false, false);
            request45.QueryStringParameters.Add("catalogToken", "Rushmore:PartnerProfile:Flyout", false, false);
            request45.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            StringHttpBody request45Body = new StringHttpBody();
            request45Body.ContentType = "";
            request45Body.InsertByteOrderMark = false;
            request45Body.BodyString = "";
            request45.Body = request45Body;
            yield return request45;
            request45 = null;

            WebTestRequest request46 = new WebTestRequest("https://psbc-common-pne.mbs.microsoft.com/cdn/app/widgets/customersearch/view.htm" +
                    "l");
            request46.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request46.QueryStringParameters.Add("v", "26201", false, false);
            yield return request46;
            request46 = null;

            WebTestRequest request47 = new WebTestRequest("https://psbc-svc-navigation-pne.mbs.microsoft.com/api/navigation/GetNavigationCat" +
                    "alog");
            request47.Method = "OPTIONS";
            request47.QueryStringParameters.Add("securityAccountGUID", "62b79819-5941-4a73-bdd4-cdafd7a22844", false, false);
            request47.QueryStringParameters.Add("catalogToken", "Rushmore:NavMenu:Root", false, false);
            request47.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            StringHttpBody request47Body = new StringHttpBody();
            request47Body.ContentType = "";
            request47Body.InsertByteOrderMark = false;
            request47Body.BodyString = "";
            request47.Body = request47Body;
            yield return request47;
            request47 = null;

            WebTestRequest request48 = new WebTestRequest("https://psbc-svc-navigation-pne.mbs.microsoft.com/api/navigation/GetNavigationCat" +
                    "alog");
            request48.Method = "OPTIONS";
            request48.QueryStringParameters.Add("securityAccountGUID", "62b79819-5941-4a73-bdd4-cdafd7a22844", false, false);
            request48.QueryStringParameters.Add("catalogToken", "Rushmore:Home:Quicklink", false, false);
            request48.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            StringHttpBody request48Body = new StringHttpBody();
            request48Body.ContentType = "";
            request48Body.InsertByteOrderMark = false;
            request48Body.BodyString = "";
            request48.Body = request48Body;
            yield return request48;
            request48 = null;

            WebTestRequest request49 = new WebTestRequest("https://psbc-svc-navigation-pne.mbs.microsoft.com/api/navigation/GetNavigationCat" +
                    "alog");
            request49.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request49.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request49.QueryStringParameters.Add("securityAccountGUID", "62b79819-5941-4a73-bdd4-cdafd7a22844", false, false);
            request49.QueryStringParameters.Add("catalogToken", "Rushmore:PartnerProfile:Flyout", false, false);
            request49.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            yield return request49;
            request49 = null;

            WebTestRequest request50 = new WebTestRequest("https://psbc-svc-navigation-pne.mbs.microsoft.com/api/navigation/GetNavigationCat" +
                    "alog");
            request50.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request50.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request50.QueryStringParameters.Add("securityAccountGUID", "62b79819-5941-4a73-bdd4-cdafd7a22844", false, false);
            request50.QueryStringParameters.Add("catalogToken", "Rushmore:NavMenu:Root", false, false);
            request50.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            yield return request50;
            request50 = null;

            WebTestRequest request51 = new WebTestRequest("https://psbc-svc-navigation-pne.mbs.microsoft.com/api/navigation/GetNavigationCat" +
                    "alog");
            request51.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request51.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request51.QueryStringParameters.Add("securityAccountGUID", "62b79819-5941-4a73-bdd4-cdafd7a22844", false, false);
            request51.QueryStringParameters.Add("catalogToken", "Rushmore:Home:Quicklink", false, false);
            request51.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            yield return request51;
            request51 = null;

            WebTestRequest request52 = new WebTestRequest("https://businesscenter-pne.mbs.microsoft.com/cdn/App/views/firmListFlyoutMenu.htm" +
                    "l");
            request52.Headers.Add(new WebTestRequestHeader("Referer", "https://businesscenter-pne.mbs.microsoft.com/#"));
            request52.QueryStringParameters.Add("v", "26201", false, false);
            yield return request52;
            request52 = null;

            WebTestRequest request53 = new WebTestRequest("https://psbc-svc-organization-pne.mbs.microsoft.com/api/odata/CompanyRelationship" +
                    "");
            request53.Method = "OPTIONS";
            request53.QueryStringParameters.Add("$filter", "((((AccountTypeId%20eq%20245)%20or%20(AccountTypeId%20eq%20252))%20or%20(AccountT" +
                    "ypeId%20eq%20255))%20or%20(AccountTypeId%20eq%203511))%20and%20(OrganizationLeve" +
                    "lId%20eq%2015214)", false, false);
            request53.QueryStringParameters.Add("$expand", "Addresses", false, false);
            request53.QueryStringParameters.Add("filterCompanyGuid", "6cecf32f-b97d-4960-80ee-1dfbf9fa668c", false, false);
            StringHttpBody request53Body = new StringHttpBody();
            request53Body.ContentType = "";
            request53Body.InsertByteOrderMark = false;
            request53Body.BodyString = "";
            request53.Body = request53Body;
            yield return request53;
            request53 = null;

            this.BeginTransaction("1-Login");
            yield break;

            this.EndTransaction("1-Login");
        }
    }
}
