//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTWebAndLoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest13Coded : WebTest
    {

        public WebTest13Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                    "");
            request1.ThinkTime = 3;
            request1.ExpectedResponseUrl = @"https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.partners.extranet.microsoft.com&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fSelectProfile.aspx%253fReturnURL%253dhttps%25253a%25252f%25252fmbs2-pne.partners.extranet.microsoft.com%25252fMSVoice%25252fOrganizationMapping.aspx%25253fe%25253dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK&wct=2016-04-25T09%3a44%3a24Z";
            request1.QueryStringParameters.Add("e", "OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK", false, false);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request1.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            ExtractText extractionRule2 = new ExtractText();
            extractionRule2.StartsWith = "&amp;wct=";
            extractionRule2.EndsWith = "\"";
            extractionRule2.Index = 0;
            extractionRule2.IgnoreCase = false;
            extractionRule2.UseRegularExpression = false;
            extractionRule2.HtmlDecode = true;
            extractionRule2.Required = false;
            extractionRule2.ContextParameterName = "QueryStringParam14.wct";
            request1.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://corp.sts.microsoft.com/adfs/ls/");
            request2.Method = "POST";
            request2.ExpectedResponseUrl = "https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp.sts.micr" +
                "osoft.com&wctx=aa4de896-3aac-4a27-a896-8e10a6a755a2&wct=2016-04-25T09%3a44%3a24Z" +
                "";
            request2.Headers.Add(new WebTestRequestHeader("Referer", @"https://corp.sts.microsoft.com/adfs/ls/?wa=wsignin1.0&wtrealm=urn%3ambs2-pne.partners.extranet.microsoft.com&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fSelectProfile.aspx%253fReturnURL%253dhttps%25253a%25252f%25252fmbs2-pne.partners.extranet.microsoft.com%25252fMSVoice%25252fOrganizationMapping.aspx%25253fe%25253dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK&wct=2016-04-25T09%3a44%3a24Z"));
            request2.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            request2.QueryStringParameters.Add("wtrealm", "urn%3ambs2-pne.partners.extranet.microsoft.com", false, false);
            request2.QueryStringParameters.Add("wctx", @"rm%3d0%26id%3dpassive%26ru%3d%252fUserInfo%252fSelectProfile.aspx%253fReturnURL%253dhttps%25253a%25252f%25252fmbs2-pne.partners.extranet.microsoft.com%25252fMSVoice%25252fOrganizationMapping.aspx%25253fe%25253dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK", false, false);
            request2.QueryStringParameters.Add("wct", this.Context["QueryStringParam14.wct"].ToString(), false, false);
            FormPostHttpBody request2Body = new FormPostHttpBody();
            request2Body.FormPostParameters.Add("__EVENTTARGET", "CustomHRD$LinkButton_LiveId");
            request2Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request2Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request2Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request2Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request2Body.FormPostParameters.Add("__db", this.Context["$HIDDEN1.__db"].ToString());
            request2Body.FormPostParameters.Add("CustomHRD$emailTB", "alias@fabrikam.com");
            request2.Body = request2Body;
            ExtractHiddenFields extractionRule3 = new ExtractHiddenFields();
            extractionRule3.Required = true;
            extractionRule3.HtmlDecode = true;
            extractionRule3.ContextParameterName = "1";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            ExtractText extractionRule4 = new ExtractText();
            extractionRule4.StartsWith = "&wctx=";
            extractionRule4.EndsWith = "&";
            extractionRule4.Index = 4;
            extractionRule4.IgnoreCase = false;
            extractionRule4.UseRegularExpression = false;
            extractionRule4.HtmlDecode = true;
            extractionRule4.Required = false;
            extractionRule4.ContextParameterName = "QueryStringParam6.wctx";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule4.Extract);
            ExtractText extractionRule5 = new ExtractText();
            extractionRule5.StartsWith = "&wct=";
            extractionRule5.EndsWith = "&";
            extractionRule5.Index = 3;
            extractionRule5.IgnoreCase = false;
            extractionRule5.UseRegularExpression = false;
            extractionRule5.HtmlDecode = true;
            extractionRule5.Required = false;
            extractionRule5.ContextParameterName = "QueryStringParam7.wct";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule5.Extract);
            ExtractText extractionRule6 = new ExtractText();
            extractionRule6.StartsWith = "&bk=";
            extractionRule6.EndsWith = "&";
            extractionRule6.Index = 3;
            extractionRule6.IgnoreCase = false;
            extractionRule6.UseRegularExpression = false;
            extractionRule6.HtmlDecode = true;
            extractionRule6.Required = false;
            extractionRule6.ContextParameterName = "QueryStringParam8.bk";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule6.Extract);
            ExtractText extractionRule7 = new ExtractText();
            extractionRule7.StartsWith = "&uaid=";
            extractionRule7.EndsWith = "&";
            extractionRule7.Index = 0;
            extractionRule7.IgnoreCase = false;
            extractionRule7.UseRegularExpression = false;
            extractionRule7.HtmlDecode = true;
            extractionRule7.Required = false;
            extractionRule7.ContextParameterName = "QueryStringParam9.uaid";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule7.Extract);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://login.live.com/ppsecure/post.srf");
            request3.Method = "POST";
            request3.Headers.Add(new WebTestRequestHeader("Referer", "https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp.sts.micr" +
                        "osoft.com&wctx=aa4de896-3aac-4a27-a896-8e10a6a755a2&wct=2016-04-25T09%3a44%3a24Z" +
                        ""));
            request3.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            request3.QueryStringParameters.Add("wtrealm", "http%3a%2f%2fcorp.sts.microsoft.com", false, false);
            request3.QueryStringParameters.Add("wctx", this.Context["QueryStringParam6.wctx"].ToString(), false, false);
            request3.QueryStringParameters.Add("wct", this.Context["QueryStringParam7.wct"].ToString(), false, false);
            request3.QueryStringParameters.Add("bk", this.Context["QueryStringParam8.bk"].ToString(), false, false);
            request3.QueryStringParameters.Add("uaid", this.Context["QueryStringParam9.uaid"].ToString(), false, false);
            request3.QueryStringParameters.Add("pid", "0", false, false);
            FormPostHttpBody request3Body = new FormPostHttpBody();
            request3Body.FormPostParameters.Add("loginfmt", "px3rajesh@outlook.com");
            request3Body.FormPostParameters.Add("login", "px3rajesh@outlook.com");
            request3Body.FormPostParameters.Add("passwd", "rajeshpx3");
            request3Body.FormPostParameters.Add("type", "11");
            request3Body.FormPostParameters.Add("PPFT", this.Context["$HIDDEN1.PPFT"].ToString());
            request3Body.FormPostParameters.Add("PPSX", "PassportRN");
            request3Body.FormPostParameters.Add("NewUser", "1");
            request3Body.FormPostParameters.Add("LoginOptions", "3");
            request3Body.FormPostParameters.Add("FoundMSAs", "");
            request3Body.FormPostParameters.Add("fspost", "0");
            request3Body.FormPostParameters.Add("i2", "1");
            request3Body.FormPostParameters.Add("i16", @"{""navigationStart"":1461577469353,""unloadEventStart"":0,""unloadEventEnd"":0,""redirectStart"":0,""redirectEnd"":0,""fetchStart"":1461577469717,""domainLookupStart"":1461577469717,""domainLookupEnd"":1461577469717,""connectStart"":1461577469717,""connectEnd"":1461577469717,""requestStart"":1461577470814,""responseStart"":1461577471093,""responseEnd"":1461577471094,""domLoading"":1461577471093,""domInteractive"":1461577471384,""domContentLoadedEventStart"":1461577471384,""domContentLoadedEventEnd"":1461577471384,""domComplete"":1461577471388,""loadEventStart"":1461577471391,""loadEventEnd"":0,""msFirstPaint"":0}");
            request3Body.FormPostParameters.Add("i17", "0");
            request3Body.FormPostParameters.Add("i18", "__DefaultLogin_Strings|1,__DefaultLogin_Core|1,");
            request3Body.FormPostParameters.Add("i19", "14966");
            request3Body.FormPostParameters.Add("i21", "0");
            request3Body.FormPostParameters.Add("i22", "0");
            request3Body.FormPostParameters.Add("i13", "0");
            request3.Body = request3Body;
            ExtractHiddenFields extractionRule8 = new ExtractHiddenFields();
            extractionRule8.Required = true;
            extractionRule8.HtmlDecode = true;
            extractionRule8.ContextParameterName = "1";
            request3.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule8.Extract);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://corp.sts.microsoft.com/adfs/ls/");
            request4.Method = "POST";
            request4.Headers.Add(new WebTestRequestHeader("Referer", "https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&wtrealm=http%3a%2f%2fcorp." +
                        "sts.microsoft.com&wctx=aa4de896-3aac-4a27-a896-8e10a6a755a2&wct=2016-04-25T09%3a" +
                        "44%3a24Z&bk=1461577470&uaid=8493b74c390b45ebb8752bc34c35e5bb&pid=0"));
            FormPostHttpBody request4Body = new FormPostHttpBody();
            request4Body.FormPostParameters.Add("wctx", this.Context["$HIDDEN1.wctx"].ToString());
            request4Body.FormPostParameters.Add("NAP", this.Context["$HIDDEN1.NAP"].ToString());
            request4Body.FormPostParameters.Add("wresult", this.Context["$HIDDEN1.wresult"].ToString());
            request4Body.FormPostParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString());
            request4Body.FormPostParameters.Add("ANON", this.Context["$HIDDEN1.ANON"].ToString());
            request4.Body = request4Body;
            ExtractHiddenFields extractionRule9 = new ExtractHiddenFields();
            extractionRule9.Required = true;
            extractionRule9.HtmlDecode = true;
            extractionRule9.ContextParameterName = "1";
            request4.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule9.Extract);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/");
            request5.Method = "POST";
            request5.ExpectedResponseUrl = "https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx?Retu" +
                "rnURL=https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganiz" +
                "ationMapping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK";
            request5.Headers.Add(new WebTestRequestHeader("Referer", "https://corp.sts.microsoft.com/adfs/ls/"));
            FormPostHttpBody request5Body = new FormPostHttpBody();
            request5Body.FormPostParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString());
            request5Body.FormPostParameters.Add("wresult", this.Context["$HIDDEN1.wresult"].ToString());
            request5Body.FormPostParameters.Add("wctx", this.Context["$HIDDEN1.wctx"].ToString());
            request5.Body = request5Body;
            ExtractHiddenFields extractionRule10 = new ExtractHiddenFields();
            extractionRule10.Required = true;
            extractionRule10.HtmlDecode = true;
            extractionRule10.ContextParameterName = "1";
            request5.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule10.Extract);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx");
            request6.Method = "POST";
            request6.ExpectedResponseUrl = "https://mbs2-pne.partners.extranet.microsoft.com/MBSShare/SetLocale.aspx?ReturnUR" +
                "L=https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganizatio" +
                "nMapping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK";
            request6.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx?Retu" +
                        "rnURL=https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganiz" +
                        "ationMapping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK"));
            request6.QueryStringParameters.Add("ReturnURL", "https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganizationMa" +
                    "pping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK", false, false);
            FormPostHttpBody request6Body = new FormPostHttpBody();
            request6Body.FormPostParameters.Add("hiddenNetworkDomainGroupID", this.Context["$HIDDEN1.hiddenNetworkDomainGroupID"].ToString());
            request6Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request6Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request6Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request6Body.FormPostParameters.Add("radioGroup", "2562063");
            request6Body.FormPostParameters.Add("continueButton", "Continue");
            request6.Body = request6Body;
            ExtractHiddenFields extractionRule11 = new ExtractHiddenFields();
            extractionRule11.Required = true;
            extractionRule11.HtmlDecode = true;
            extractionRule11.ContextParameterName = "1";
            request6.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule11.Extract);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/MBSShare/SetLocale.aspx");
            request7.Method = "POST";
            request7.ExpectedResponseUrl = "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                "?e=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK";
            request7.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MBSShare/SetLocale.aspx?ReturnUR" +
                        "L=https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganizatio" +
                        "nMapping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK"));
            request7.QueryStringParameters.Add("ReturnURL", "https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganizationMa" +
                    "pping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK", false, false);
            FormPostHttpBody request7Body = new FormPostHttpBody();
            request7Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request7Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request7.Body = request7Body;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                    "etails.aspx");
            request8.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                        "?e=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK"));
            request8.QueryStringParameters.Add("qs", "OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYWPSSLWMKRMONMZMPW" +
                    "NXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM", false, false);
            WebTestRequest request8Dependent1 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request8Dependent1.Method = "OPTIONS";
            StringHttpBody request8Dependent1Body = new StringHttpBody();
            request8Dependent1Body.ContentType = "";
            request8Dependent1Body.InsertByteOrderMark = false;
            request8Dependent1Body.BodyString = "";
            request8Dependent1.Body = request8Dependent1Body;
            request8.DependentRequests.Add(request8Dependent1);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://partnerpayeeportal-int.azurewebsites.net/Home/Initalize/7acd66a4-ccf8-443" +
                    "0-84d5-d45c9f4f3435/OTY4YzdmOTYtYzYxZS00ZjczLTg4YzMtODQ0ZWYxMDRiYTRk0/en-us");
            request9.ExpectedResponseUrl = @"https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=https%3a%2f%2faccesscontrol.windows.net%2f&wreply=https%3a%2f%2fmsit-athena-mscertmanagerplanner.accesscontrol.windows.net%2fv2%2fwsfederation&wp=MBI_FED_SSL&wctx=cHI9d3NmZWRlcmF0aW9uJnJtPXVybiUzYWZlZGVyYXRpb24lMmZQWDMuUEkuSW50ZWdyYXRpb24mcnk9JmN4PXJtJTNkMCUyNmlkJTNkcGFzc2l2ZSUyNnJ1JTNkJTI1MmZIb21lJTI1MmZJbml0YWxpemUlMjUyZjdhY2Q2NmE0LWNjZjgtNDQzMC04NGQ1LWQ0NWM5ZjRmMzQzNSUyNTJmT1RZNFl6ZG1PVFl0WXpZeFpTMDBaamN6TFRnNFl6TXRPRFEwWldZeE1EUmlZVFJrMCUyNTJmZW4tdXM1";
            request9.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                        "etails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYW" +
                        "PSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM"));
            WebTestRequest request9Dependent1 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request9Dependent1.Method = "OPTIONS";
            StringHttpBody request9Dependent1Body = new StringHttpBody();
            request9Dependent1Body.ContentType = "";
            request9Dependent1Body.InsertByteOrderMark = false;
            request9Dependent1Body.BodyString = "";
            request9Dependent1.Body = request9Dependent1Body;
            request9.DependentRequests.Add(request9Dependent1);
            ExtractHiddenFields extractionRule12 = new ExtractHiddenFields();
            extractionRule12.Required = true;
            extractionRule12.HtmlDecode = true;
            extractionRule12.ContextParameterName = "1";
            request9.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule12.Extract);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://msit-athena-mscertmanagerplanner.accesscontrol.windows.net/v2/wsfederatio" +
                    "n");
            request10.Method = "POST";
            request10.Headers.Add(new WebTestRequestHeader("Referer", @"https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=https%3a%2f%2faccesscontrol.windows.net%2f&wreply=https%3a%2f%2fmsit-athena-mscertmanagerplanner.accesscontrol.windows.net%2fv2%2fwsfederation&wp=MBI_FED_SSL&wctx=cHI9d3NmZWRlcmF0aW9uJnJtPXVybiUzYWZlZGVyYXRpb24lMmZQWDMuUEkuSW50ZWdyYXRpb24mcnk9JmN4PXJtJTNkMCUyNmlkJTNkcGFzc2l2ZSUyNnJ1JTNkJTI1MmZIb21lJTI1MmZJbml0YWxpemUlMjUyZjdhY2Q2NmE0LWNjZjgtNDQzMC04NGQ1LWQ0NWM5ZjRmMzQzNSUyNTJmT1RZNFl6ZG1PVFl0WXpZeFpTMDBaamN6TFRnNFl6TXRPRFEwWldZeE1EUmlZVFJrMCUyNTJmZW4tdXM1"));
            request10.QueryStringParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString(), false, false);
            FormPostHttpBody request10Body = new FormPostHttpBody();
            request10Body.FormPostParameters.Add("wctx", this.Context["$HIDDEN1.wctx"].ToString());
            request10Body.FormPostParameters.Add("NAP", this.Context["$HIDDEN1.NAP"].ToString());
            request10Body.FormPostParameters.Add("wresult", this.Context["$HIDDEN1.wresult"].ToString());
            request10Body.FormPostParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString());
            request10Body.FormPostParameters.Add("ANON", this.Context["$HIDDEN1.ANON"].ToString());
            request10.Body = request10Body;
            ExtractHiddenFields extractionRule13 = new ExtractHiddenFields();
            extractionRule13.Required = true;
            extractionRule13.HtmlDecode = true;
            extractionRule13.ContextParameterName = "1";
            request10.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule13.Extract);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://partnerpayeeportal-int.azurewebsites.net/");
            request11.Method = "POST";
            request11.ExpectedResponseUrl = "https://partnerpayeeportal-int.azurewebsites.net/Home/Initalize/7acd66a4-ccf8-443" +
                "0-84d5-d45c9f4f3435/OTY4YzdmOTYtYzYxZS00ZjczLTg4YzMtODQ0ZWYxMDRiYTRk0/en-us";
            request11.Headers.Add(new WebTestRequestHeader("Referer", "https://msit-athena-mscertmanagerplanner.accesscontrol.windows.net/v2/wsfederatio" +
                        "n?wa=wsignin1.0"));
            FormPostHttpBody request11Body = new FormPostHttpBody();
            request11Body.FormPostParameters.Add("wa", this.Context["$HIDDEN1.wa"].ToString());
            request11Body.FormPostParameters.Add("wresult", this.Context["$HIDDEN1.wresult"].ToString());
            request11Body.FormPostParameters.Add("wctx", this.Context["$HIDDEN1.wctx"].ToString());
            request11.Body = request11Body;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://partnerpayeeportal-int.azurewebsites.net/Home/Locations/2382249/b1040434-" +
                    "30bb-40f0-a498-c3338d73845c");
            request12.Headers.Add(new WebTestRequestHeader("Referer", "https://partnerpayeeportal-int.azurewebsites.net/Home/Initalize/7acd66a4-ccf8-443" +
                        "0-84d5-d45c9f4f3435/OTY4YzdmOTYtYzYxZS00ZjczLTg4YzMtODQ0ZWYxMDRiYTRk0/en-us"));
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/library/mnp/2/aspx/js.aspx");
            request13.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/UserInfo/SelectProfile.aspx?Retu" +
                        "rnURL=https%3a%2f%2fmbs2-pne.partners.extranet.microsoft.com%2fMSVoice%2fOrganiz" +
                        "ationMapping.aspx%3fe%3dOQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK"));
            request13.QueryStringParameters.Add("", "", false, false);
            request13.QueryStringParameters.Add("name", "Menu", false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                    "/GetProfileStatus");
            request14.ThinkTime = 1;
            request14.Method = "POST";
            request14.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request14.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request14.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                        "?e=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK"));
            StringHttpBody request14Body = new StringHttpBody();
            request14Body.ContentType = "application/json; charset=utf-8";
            request14Body.InsertByteOrderMark = false;
            request14Body.BodyString = "{\"companyId\":9779672,\"programIds\":[3]}";
            request14.Body = request14Body;
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request15.Method = "POST";
            request15.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx" +
                        "?e=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSUONRUPQOYPMNRLUK"));
            StringHttpBody request15Body = new StringHttpBody();
            request15Body.ContentType = "application/json";
            request15Body.InsertByteOrderMark = false;
            request15Body.BodyString = @"[{""time"":""2016-04-25T09:45:01.232Z"",""iKey"":""67bd45d3-f647-42f8-85af-99bfdf6eac56"",""name"":""Microsoft.ApplicationInsights.67bd45d3f64742f885af99bfdf6eac56.RemoteDependency"",""tags"":{""ai.session.id"":""E2+Pl"",""ai.session.isFirst"":""true"",""ai.device.id"":""browser"",""ai.device.type"":""Browser"",""ai.internal.sdkVersion"":""JavaScript:0.22.9"",""ai.user.id"":""BdSKZ"",""ai.operation.id"":""hCK3r"",""ai.operation.name"":""/MSVoice/OrganizationMapping.aspx""},""data"":{""baseType"":""RemoteDependencyData"",""baseData"":{""id"":""XCrWN"",""ver"":2,""name"":""https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMapping.aspx/GetProfileStatus"",""kind"":1,""value"":1065.0723433954572,""dependencyKind"":1,""success"":true,""dependencySource"":2,""commandName"":""MSVoice/OrganizationMapping.aspx/GetProfileStatus"",""dependencyTypeName"":""Ajax"",""properties"":{},""resultCode"":""200""}}}]";
            request15.Body = request15Body;
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                    "etails.aspx/GetProfileStatus");
            request16.Method = "POST";
            request16.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request16.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request16.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                        "etails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYW" +
                        "PSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM"));
            StringHttpBody request16Body = new StringHttpBody();
            request16Body.ContentType = "application/json; charset=utf-8";
            request16Body.InsertByteOrderMark = false;
            request16Body.BodyString = "{\"companyId\":9779672,\"programId\":\"3\",\"selectedMpnId\":\"2382250\"}";
            request16.Body = request16Body;
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request17.Method = "OPTIONS";
            StringHttpBody request17Body = new StringHttpBody();
            request17Body.ContentType = "";
            request17Body.InsertByteOrderMark = false;
            request17Body.BodyString = "";
            request17.Body = request17Body;
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request18.ThinkTime = 2;
            request18.Method = "POST";
            request18.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                        "etails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYW" +
                        "PSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM"));
            StringHttpBody request18Body = new StringHttpBody();
            request18Body.ContentType = "application/json";
            request18Body.InsertByteOrderMark = false;
            request18Body.BodyString = "[{\"time\":\"2016-04-25T09:45:03.502Z\",\"iKey\":\"67bd45d3-f647-42f8-85af-99bfdf6eac56\"" +
                ",\"name\":\"Microsoft.ApplicationInsights.67bd45d3f64742f885af99bfdf6eac56.Pageview" +
                "\",\"tags\":{\"ai.session.id\":\"E2+Pl\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Bro" +
                "wser\",\"ai.internal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"BdSKZ\",\"ai.oper" +
                "ation.id\":\"4/2sH\",\"ai.operation.name\":\"/MSVoice/OrganizationMappingBankDetails.a" +
                "spx\"},\"data\":{\"baseType\":\"PageviewData\",\"baseData\":{\"ver\":2,\"name\":\"Banking and " +
                "Tax Enrollment\",\"url\":\"https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/" +
                "OrganizationMappingBankDetails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMW" +
                "YNLOZNKQRTTQYKRROZXYRTYWPSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQ" +
                "QSOZLLTXPUOUYRLQZLRQUOM\",\"duration\":\"00:00:01.053\"}}},{\"time\":\"2016-04-25T09:45:" +
                "03.506Z\",\"iKey\":\"67bd45d3-f647-42f8-85af-99bfdf6eac56\",\"name\":\"Microsoft.Applica" +
                "tionInsights.67bd45d3f64742f885af99bfdf6eac56.PageviewPerformance\",\"tags\":{\"ai.s" +
                "ession.id\":\"E2+Pl\",\"ai.device.id\":\"browser\",\"ai.device.type\":\"Browser\",\"ai.inter" +
                "nal.sdkVersion\":\"JavaScript:0.22.9\",\"ai.user.id\":\"BdSKZ\",\"ai.operation.id\":\"4/2s" +
                "H\",\"ai.operation.name\":\"/MSVoice/OrganizationMappingBankDetails.aspx\"},\"data\":{\"" +
                "baseType\":\"PageviewPerformanceData\",\"baseData\":{\"ver\":2,\"name\":\"Banking and Tax " +
                "Enrollment\",\"url\":\"https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/Orga" +
                "nizationMappingBankDetails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLO" +
                "ZNKQRTTQYKRROZXYRTYWPSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZ" +
                "LLTXPUOUYRLQZLRQUOM\",\"duration\":\"00:00:01.053\",\"perfTotal\":\"00:00:01.053\",\"netwo" +
                "rkConnect\":\"00:00:00.005\",\"sentRequest\":\"00:00:00.002\",\"receivedResponse\":\"00:00" +
                ":00.005\",\"domProcessing\":\"00:00:00.246\"}}}]";
            request18.Body = request18Body;
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://dc.services.visualstudio.com/v2/track");
            request19.Method = "POST";
            request19.Headers.Add(new WebTestRequestHeader("Referer", "https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankD" +
                        "etails.aspx?qs=OQZSRROYTXYYRRQWMTVPQNQYVUSTRLWSZXMXMWNMWYNLOZNKQRTTQYKRROZXYRTYW" +
                        "PSSLWMKRMONMZMPWNXNKKQOTQTRZXYNUSPUQMKNUZQSTZXVMXQQUVOLQQSOZLLTXPUOUYRLQZLRQUOM"));
            StringHttpBody request19Body = new StringHttpBody();
            request19Body.ContentType = "application/json";
            request19Body.InsertByteOrderMark = false;
            request19Body.BodyString = @"[{""time"":""2016-04-25T09:45:04.379Z"",""iKey"":""67bd45d3-f647-42f8-85af-99bfdf6eac56"",""name"":""Microsoft.ApplicationInsights.67bd45d3f64742f885af99bfdf6eac56.RemoteDependency"",""tags"":{""ai.session.id"":""E2+Pl"",""ai.device.id"":""browser"",""ai.device.type"":""Browser"",""ai.internal.sdkVersion"":""JavaScript:0.22.9"",""ai.user.id"":""BdSKZ"",""ai.operation.id"":""4/2sH"",""ai.operation.name"":""/MSVoice/OrganizationMappingBankDetails.aspx""},""data"":{""baseType"":""RemoteDependencyData"",""baseData"":{""id"":""DaUSd"",""ver"":2,""name"":""https://mbs2-pne.partners.extranet.microsoft.com/MSVoice/OrganizationMappingBankDetails.aspx/GetProfileStatus"",""kind"":1,""value"":989.4425855717443,""dependencyKind"":1,""success"":true,""dependencySource"":2,""commandName"":""MSVoice/OrganizationMappingBankDetails.aspx/GetProfileStatus"",""dependencyTypeName"":""Ajax"",""properties"":{},""resultCode"":""200""}}}]";
            request19.Body = request19Body;
            yield return request19;
            request19 = null;
        }
    }
}
