// <auto-generated />
namespace DMP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class photourlx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(photourlx));
        
        string IMigrationMetadata.Id
        {
            get { return "201510080649482_photourlx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
