// <auto-generated />
namespace DMP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class photourl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(photourl));
        
        string IMigrationMetadata.Id
        {
            get { return "201510071531486_photourl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
