// <auto-generated />
namespace DMP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class membername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(membername));
        
        string IMigrationMetadata.Id
        {
            get { return "201510080739372_membername"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
