//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICreditLimitResponse")]
    public interface ICreditLimitResponse {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICreditLimitResponse/SendCreditLimitResponse")]
        void SendCreditLimitResponse(double limit);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICreditLimitResponse/SendCreditLimitResponse")]
        System.Threading.Tasks.Task SendCreditLimitResponseAsync(double limit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditLimitResponseChannel : WindowsFormsApplication1.ServiceReference.ICreditLimitResponse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditLimitResponseClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference.ICreditLimitResponse>, WindowsFormsApplication1.ServiceReference.ICreditLimitResponse {
        
        public CreditLimitResponseClient() {
        }
        
        public CreditLimitResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditLimitResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditLimitResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditLimitResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendCreditLimitResponse(double limit) {
            base.Channel.SendCreditLimitResponse(limit);
        }
        
        public System.Threading.Tasks.Task SendCreditLimitResponseAsync(double limit) {
            return base.Channel.SendCreditLimitResponseAsync(limit);
        }
    }
}
