// <auto-generated />
namespace RU.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class chapter4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chapter4));
        
        string IMigrationMetadata.Id
        {
            get { return "201511170822404_chapter4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
